import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const translations = {
  en: {
    // Nav
    getInTouch: 'Get in Touch',
    search: 'Search Proxynet…',
    home: 'Home',
    about: 'About',
    solutions: 'Solutions',
    casestudies: 'Case Studies',
    support: 'Support',
    community: 'Community',
    blog: 'Blog',
    connectivity: 'Connectivity',
    infrastructure: 'Infrastructure',
    managedServices: 'Managed Services',
    internetServices: 'Internet Services',
    vsatSolutions: 'VSAT Solutions',
    dataCentre: 'Data Centre',
    cybersecurity: 'Cybersecurity',
    itSupport: 'IT Support',
    cloudServices: 'Cloud Services',
    // Solutions (real)
    solAV: 'Professional AV Solutions',
    solCybersecurity: 'IT Security & Cybersecurity',
    solNetworking: 'Network Infrastructure & Systems Integration',
    solEnterpriseSoftware: 'Enterprise Software Solutions',
    solUnifiedComms: 'Unified Communications',
    solCloud: 'Cloud & Managed Services',
    solCAD: 'CAD Services',
    solIoT: 'IoT & Smart Infrastructure',
    solProVMS: 'Visitor Management — ProVMS',
    solProSkool: 'School Management — ProSkool',
    solERP: 'ERP Solutions',
    solDistribution: 'Distribution & Reseller Services',
    // Software
    softwareSolutions: 'Software Solutions',
    customDev: 'Custom Software Development',
    webApps: 'Web Applications',
    mobileApps: 'Mobile Applications',
    erp: 'ERP Solutions',
    // Rentals & Billboard
    rentals: 'AV Equipment Rentals',
    rentalsDesc: 'World-class AV equipment for events and activations.',
    billboardSolutions: 'Billboard & Digital Signage',
    billboardDesc: 'Indoor and outdoor digital signage and LED wall deployments.',
    // EdTech
    edtech: 'EdTech & Smart Schools',
    edtechDesc: 'Smart school solutions, digital literacy programmes, and technology training.',
    // Footer
    footerTagline: "Connecting Nigeria's future with world-class technology infrastructure and managed services.",
    company: 'Company',
    aboutUs: 'About Us',
    ourTeam: 'Our Team',
    careers: 'Careers',
    newsPress: 'News & Press',
    partners: 'Partners',
    resources: 'Resources',
    whitepapers: 'Whitepapers',
    supportCentre: 'Support Centre',
    faqs: 'FAQs',
    contact: 'Contact',
    stayUpdated: 'Stay updated',
    emailPlaceholder: 'Your email address',
    thankYou: 'Thanks for subscribing!',
    privacyPolicy: 'Privacy Policy',
    cookiePolicy: 'Cookie Policy',
    terms: 'Terms & Conditions',
    copyright: `© ${new Date().getFullYear()} Proxynet Group Ltd. RC 472270. All rights reserved.`,
    // Home
    heroEyebrow: 'Enterprise Technology Solutions',
    heroTitle: 'Powering Africa\'s',
    heroTitleAccent: 'Digital Future',
    heroSub: 'World-class connectivity, infrastructure, and managed services for businesses across Africa — built for reliability, designed for growth.',
    exploreSolutions: 'Explore Solutions',
    // Final CTA
    finalCtaHeading: 'Ready to Transform Your IT Infrastructure?',
    finalCtaSub: 'Talk to our team and get a solution tailored to your business needs.',
    // Projects
    projectsEyebrow: 'Featured Projects',
    projectsHeading: 'Work We\'re Proud Of',
    // Blog
    latestInsights: 'Latest Insights',
    viewAll: 'View all posts',
    readMore: 'Read more',
    // Support CTA
    supportEyebrow: 'Customer Success',
    supportHeading: "We don't just deploy, we support you.",
    supportSub: "Our relationship doesn't end at installation. We provide ongoing support, monitoring, and maintenance to ensure your technology keeps working — long after the project is delivered.",
    supportCTALabel: 'Visit our Support Centre',
    supportPillar1: '24/7 monitoring and incident response',
    supportPillar2: 'Dedicated support engineers on call',
    supportPillar3: 'Long-term partnerships, not one-off projects',
    // Industries
    industriesEyebrow: 'Industries We Serve',
    industriesHeading: 'Built for the Sectors That Drive Africa\'s Economy',
    industriesSub: 'We\'ve delivered technology solutions across a wide range of industries — each with its own demands, regulations, and infrastructure challenges.',
    indFinancial: 'Financial Services',
    indFinancialDesc: 'Secure networks and compliance-ready infrastructure for banks and fintechs.',
    indOilGas: 'Oil & Gas',
    indOilGasDesc: 'Rugged connectivity and monitoring systems for upstream and downstream operations.',
    indManufacturing: 'Manufacturing',
    indManufacturingDesc: 'Systems integration and network solutions for factory floors and supply chains.',
    indTelecoms: 'Telecoms',
    indTelecomsDesc: 'Enterprise networking and managed services for telecoms operators.',
    indGovernment: 'Government',
    indGovernmentDesc: 'Secure, scalable IT infrastructure for public sector agencies and ministries.',
    indEducation: 'Education',
    indEducationDesc: 'Campus networks, smart classrooms, and e-learning infrastructure.',
    indHealthcare: 'Healthcare',
    indHealthcareDesc: 'Reliable connectivity and data security for hospitals and clinics.',
    indRetail: 'Retail',
    indRetailDesc: 'Smart signage, POS networks, and digital infrastructure for retail environments.',
    // What We Do
    whatWeDoEyebrow: 'What We Do',
    whatWeDoHeading: 'We Build & Manage Technology Infrastructure',
    whatWeDoClarity: 'We design, deploy, and support the technology systems that keep your business running — from networks and security to software and smart displays.',
    justSoYouKnow: 'Just so you know',
    whatWeDoExplainer: 'Proxynet is a technology solutions company — not an events organiser. We help businesses across Africa build reliable IT infrastructure, secure their networks, and develop software. If you\'ve heard otherwise, we\'re glad you\'re here to find out what we actually do.',
    lfdSignage: 'LFD & Smart Signage',
    lfdSignageDesc: 'Large format display systems for boardrooms, lobbies, and public spaces.',
    lfdSignageDetail: 'We design and install large format display (LFD) and smart signage solutions — from single-screen boardroom setups to multi-zone digital signage networks across campuses and retail environments.',
    systemsIntegration: 'Systems Integration',
    systemsIntegrationDesc: 'Connecting your hardware, software, and networks into one seamless system.',
    systemsIntegrationDetail: 'We integrate disparate technology systems so they communicate and work together — reducing manual processes, eliminating data silos, and giving your team a unified view of operations.',
    enterpriseSoftware: 'Enterprise Software Development',
    enterpriseSoftwareDesc: 'Custom business applications built around your workflows.',
    enterpriseSoftwareDetail: 'From ERP systems to bespoke internal tools, we develop enterprise software that fits how your organisation actually works — not the other way around.',
    enterpriseNetworking: 'Enterprise Networking',
    enterpriseNetworkingDesc: 'LAN, MAN, and WAN solutions designed for performance and reliability.',
    enterpriseNetworkingDetail: 'We design and implement scalable network infrastructure — local area networks, wide area networks, and everything in between — built to handle your current load and grow with you.',
    networkSecurity: 'Network Security',
    networkSecurityDesc: 'Protecting your infrastructure from threats, inside and out.',
    networkSecurityDetail: 'Our security team implements firewalls, intrusion detection systems, anti-virus solutions, and VPNs to protect your organisation from both external attacks and internal vulnerabilities.',
    disasterRecovery: 'Disaster Recovery',
    disasterRecoveryDesc: 'Keeping your data safe and your business running when things go wrong.',
    disasterRecoveryDetail: 'We plan, implement, and regularly test disaster recovery strategies so that when the unexpected happens — hardware failure, cyberattack, or natural disaster — your business recovers fast.',
    enterpriseNetworkingWan: 'Remote Access & VPN',
    enterpriseNetworkingWanDesc: 'Secure connectivity for teams working from anywhere.',
    enterpriseNetworkingWanDetail: 'We implement remote access solutions and VPN infrastructure that let your team connect securely to company systems from any location, without compromising security.',
    mobileAppsDesc: 'iOS and Android applications built for business.',
    mobileAppsDetail: 'We build mobile applications that extend your business capabilities to smartphones and tablets — whether customer-facing apps or internal tools for field teams.',
    // Industries CTAs
    findYourSolution: 'Find Your Solution',
    contactSales: 'Contact Sales',
    // Cookie Banner
    cookieTitle: 'We use cookies',
    cookieBody: 'We use cookies to improve your experience on our website, analyse traffic, and personalise content. By clicking "Accept", you consent to our use of cookies in accordance with our',
    cookieAnd: 'and',
    cookieCompliance: 'This site complies with the Nigeria Data Protection Regulation (NDPR) and GDPR.',
    cookieDecline: 'Decline',
    cookieAccept: 'Accept All',
    // Testimonials / Partners placeholders
    testimonialsHeading: 'Testimonials',
    partnersHeading: 'Our Partners',
    // Featured Projects CTAs
    startAProject: 'Start a Project',
    viewCaseStudies: 'View Case Studies',
    // About CTA
    readyToWorkWithUs: 'Ready to work with us?',
    aboutCtaSub: "Talk to our team about your technology needs — we'll build a solution around your business.",
    contactUs: 'Contact Us',
    viewOurSolutions: 'View Our Solutions',
    // Contact page
    contactNav: 'Contact',
    contactPageTitle: 'Contact Us — Let\'s Talk Technology',
    contactPageDesc: 'Get in touch with Proxynet Group. Reach our sales, support, partnerships, or careers teams. Offices in Lagos, Abuja, Accra, Abidjan, and Dubai.',
    contactHeroTitle: 'Let\'s Talk Technology',
    contactHeroSub: 'Whether you\'re ready to start a project, need technical support, or just want to explore what\'s possible — our team is ready to help.',
    contactCtaPrimary: 'Send an Enquiry',
    contactCtaSecondary: 'Call Us Now',
    contactResponseTime: 'We respond to all enquiries within 4 business hours. Critical support issues are handled 24/7.',
    contactFormEyebrow: 'Send a Message',
    contactFormHeading: 'How Can We Help?',
    contactSuccessTitle: 'Enquiry Sent',
    contactSuccessMsg: 'Thank you for reaching out. Our team will get back to you within 4 business hours.',
    contactFieldName: 'Full Name',
    contactFieldCompany: 'Company',
    contactFieldEmail: 'Email Address',
    contactFieldPhone: 'Phone Number',
    contactFieldType: 'Enquiry Type',
    contactFieldTypeDefault: 'Select enquiry type',
    contactTypeSales: 'Sales',
    contactTypeSupport: 'Technical Support',
    contactTypePartnership: 'Partnerships',
    contactTypeCareers: 'Careers',
    contactTypeGeneral: 'General',
    contactFieldMessage: 'Message',
    contactFieldMessagePlaceholder: 'Tell us about your project, challenge, or question…',
    contactSubmit: 'Send Enquiry',
    contactDirectEyebrow: 'Direct Contacts',
    contactDirectHeading: 'Reach the Right Team',
    contactPhone: 'Main Line',
    contactPhoneAlt: 'Alternate Line',
    contactEmail: 'Email',
    contactFollowUs: 'Follow Us',
    // Locations
    contactThisOffice: 'Contact This Office',
    viewOnMap: 'View on Map',
    // Not Found
    pageNotFound: 'Page Not Found',
    pageNotFoundSub: 'The page you are looking for does not exist or has been moved. Let us get you back on track.',
    backToHomepage: 'Back to Homepage',
    goBack: 'Go Back',
    // Careers
    viewOpenRoles: 'View Open Roles',
    learnAboutCulture: 'Learn About Our Culture',
    applyForGraduate: 'Apply for Graduate Programme',
    applyForInternship: 'Apply for Internship',
    apply: 'Apply',
    submitApplication: 'Submit Application',
    // Support
    raiseATicket: 'Raise a Ticket',
    callSupportNow: 'Call Support Now',
    requestAccess: 'Request Access',
    submitRequest: 'Submit Request',
    // Blog
    readLatestPosts: 'Read Latest Posts',
    subscribeForUpdates: 'Subscribe for Updates',
    subscribe: 'Subscribe',
    // EdTech
    partnerWithUs: 'Partner With Us',
    viewProgrammes: 'View Programmes',
    visitEdTechWebsite: 'Visit the EdTech Website',
    submitEnquiry: 'Submit Enquiry',
    // Billboard / Rentals
    requestAQuote: 'Request a Quote',
    requestARental: 'Request a Rental',
    viewEquipment: 'View Equipment',
    // Navbar solutions mega menu categories
    catAVInfra: 'AV & Infrastructure',
    catSoftwareApps: 'Software & Apps',
    catManagedCloud: 'Managed & Cloud',
    catSpecialist: 'Specialist',
    // Featured Projects content
    proj1Solution: '15-Display NOC Solution',
    proj1Category: 'NOC & Command Centre',
    proj1Outcome: 'Deployed a 15-screen network operations centre enabling real-time monitoring across UBA infrastructure.',
    proj2Solution: '4x2 46-Inch Videowall with NOC Monitoring Solution',
    proj2Category: 'Videowall & NOC',
    proj2Outcome: 'Installed a high-resolution 8-panel videowall for centralised network and security monitoring.',
    proj3Solution: 'Command Center Solution for Link Health and Infrastructure Monitoring',
    proj3Category: 'Design, Deployment & Support',
    proj3Outcome: 'End-to-end command center solution for monitoring link health and infrastructure across the university campus.',
    proj4Solution: '32-Display NOC Solution',
    proj4Category: 'NOC & Command Centre',
    proj4Outcome: 'Deployed a 32-screen network operations centre for Access Bank DIG, enabling comprehensive infrastructure monitoring.',
    proj5Solution: 'NOC VideoWall with Peerless VideoWall Floor Stand',
    proj5Category: 'Videowall & NOC',
    proj5Outcome: 'Installed a high-resolution NOC videowall with Peerless floor stand at FCMB Lagos headquarters.',
    proj6Solution: 'Command Center Solution for Infrastructure Monitoring',
    proj6Category: 'Design, Deployment & Support',
    proj6Outcome: 'Deployed a command center solution for infrastructure monitoring at ePROCESS offices in Accra, Ghana.',
    proj7Solution: 'Multi-Site Logitech VC Solution',
    proj7Category: 'AV & Collaboration',
    proj7Outcome: 'Implemented a multi-site Logitech video conferencing solution across Lagos, Bonny, Port Harcourt, and Abuja.',
    // About page
    aboutUs: 'About Us',
    aboutHeroTitle: 'Who We Are',
    aboutHeroSub: 'Two decades of building the technology infrastructure that powers Africa\'s most ambitious organisations.',
    // SubNav
    subNavWhoWeAre: 'Who We Are',
    subNavHistory: 'History',
    subNavLeadership: 'Leadership',
    subNavAwards: 'Awards',
    subNavLocations: 'Locations',
    // Company Overview
    overviewEyebrow: 'Who We Are',
    overviewHeading: 'We\'re not a vendor. We\'re your technology partner.',
    overviewBody1: 'Proxynet Group is a Nigerian-founded technology solutions company established in 2004. We design, deploy, and support the IT infrastructure that keeps businesses running — from enterprise networks and cybersecurity to smart display systems and custom software.',
    overviewBody2: 'We work with banks, refineries, government agencies, telecoms operators, and multinationals across Nigeria, Ghana, Côte d\'Ivoire, and beyond. Our job is to make complex technology simple, reliable, and built to last.',
    overviewBody3: 'We exist because African businesses deserve world-class technology infrastructure — delivered by people who understand the local context, the infrastructure challenges, and what it takes to keep systems running in this environment.',
    // Mission & Vision
    ourMission: 'Our Mission',
    missionStatement: 'To attain and maintain leadership in the ICT Industry through the provision of the highest quality of service that will give our customers unsurpassed value in a cost effective and responsible manner — bringing value creation to the community as a whole.',
    ourVision: 'Our Vision',
    visionStatement: 'To be a definition of true success in the delivery and support of ICT Solutions globally — through the achievement of superior technology to our customer base by consistently aligning with the dynamics of the information age while setting and maintaining standards.',
    // Core Values
    coreValuesEyebrow: 'Our Values',
    coreValuesSub: 'Seven principles that guide every decision, every project, and every relationship at Proxynet.',
    cvPurposeTitle: 'Purpose Driven',
    cvPurposeDesc: 'Everything we do is anchored to a clear purpose — delivering technology that creates real, lasting value for our clients and communities.',
    cvAccountabilityTitle: 'Accountability',
    cvAccountabilityDesc: 'We own our commitments. When we say we will deliver, we deliver — and when things go wrong, we fix them without excuses.',
    cvIntegrityTitle: 'Integrity',
    cvIntegrityDesc: 'We do the right thing even when no one is watching. Our clients trust us with their critical infrastructure — we take that seriously.',
    cvDisciplineTitle: 'Discipline',
    cvDisciplineDesc: 'Excellence is not an accident. We follow proven processes, maintain high standards, and hold ourselves to consistent performance.',
    cvStewardshipTitle: 'Stewardship',
    cvStewardshipDesc: 'We treat our clients\' resources as our own — making decisions that protect their investments and build long-term value.',
    cvOnenessTitle: 'Oneness',
    cvOnenessDesc: 'We work as one team — internally and with our clients. Collaboration, not silos, is how we solve complex problems.',
    cvExemplaryTitle: 'Exemplary',
    cvExemplaryDesc: 'We set the standard. In our industry, our communities, and our conduct — we aim to be the example others follow.',
    // Timeline
    timelineEyebrow: 'Our History',
    timelineHeading: 'Two Decades of Progress',
    tm2004Title: 'Founded',
    tm2004Desc: 'Proxynet Communications established in Lagos, Nigeria with a mission to deliver world-class IT solutions.',
    tm2008Title: 'First Major Enterprise Contract',
    tm2008Desc: 'Secured first large-scale enterprise networking project with a tier-1 Nigerian bank.',
    tm2010Title: 'Regional Expansion',
    tm2010Desc: 'Opened operations in Abuja to serve federal government and public sector clients.',
    tm2012Title: 'Samsung Partnership',
    tm2012Desc: 'Became an authorised Samsung B2B partner, expanding into large format display and smart signage solutions.',
    tm2014Title: 'Samsung B2B Award',
    tm2014Desc: 'Recognised with the Samsung B2B Award for outstanding performance and client delivery.',
    tm2016Title: 'West Africa Expansion',
    tm2016Desc: 'Established presence in Ghana and Côte d\'Ivoire, serving clients across West Africa.',
    tm2019Title: 'Dubai Office',
    tm2019Desc: 'Opened Middle East office in Dubai Silicon Oasis to serve international clients and technology partners.',
    tm2024Title: '20 Years Strong',
    tm2024Desc: 'Celebrating two decades of technology excellence — 500+ projects, 6 countries, 50+ global partners.',
    // Leadership
    leadershipEyebrow: 'Leadership',
    leadershipHeading: 'The Team Behind Proxynet',
    // Awards
    awardsEyebrow: 'Recognition',
    awardsHeading: 'Awards & Certifications',
    awardsSub: 'Our partnerships and accreditations reflect the trust global technology leaders place in Proxynet.',
    // Locations
    locationsEyebrow: 'Where We Are',
    locationsHeading: 'Our Offices',
    locationsSub: 'From our Lagos headquarters to offices across West Africa and the Middle East — we\'re close to the clients we serve.',
    // Tax Compliance
    taxTitle: 'Registered & Tax-Compliant',
    taxBody: 'Proxynet Group Ltd is a duly registered Nigerian company (RC 472270) incorporated under the Companies and Allied Matters Act (CAMA). We are fully tax-compliant, hold a valid Tax Identification Number (TIN: 00775065-0001), and file all statutory returns with the Federal Inland Revenue Service (FIRS). All invoices issued by Proxynet are legally valid for procurement and audit purposes.',
    // Awards body text
    award1Body: 'Recognised by Samsung for outstanding B2B sales performance and client delivery excellence in Nigeria.',
    award2Body: 'Certified Samsung B2B partner for large format displays, smart signage, and enterprise AV solutions.',
    award3Body: 'Authorised Microsoft partner for enterprise software, cloud services, and licensing solutions.',
    award4Body: 'Authorised Canon distributor for printers, scanners, cameras, and document management solutions.',
    award5Body: 'Authorised Yealink distributor for IP phones, video conferencing, and unified communications.',
    award6Body: 'Certified Yealink system integrator for enterprise-wide UC deployments and managed services.',
    award7Body: 'Authorised Logitech partner for video collaboration, peripherals, and enterprise workspace solutions.',
    award8Body: 'Official distributor of VT professional headsets and communication devices across West Africa.',
    award9Body: 'Authorised Dahua distributor for CCTV, IP cameras, NVR systems, and security surveillance solutions.',
    award10Body: 'Quality Management System certified by TNV (Cert No. SBSCKTSI20251120NGAQM10U). Valid through 19/11/2028.',
    // Support page
    supportHeroTitle: '24/7 Support, Because Your Business Never Stops',
    supportHeroSub: 'Our support team is available around the clock to keep your technology running. Raise a ticket, call us, or reach us on WhatsApp — we respond fast.',
    supportOptRaiseTicket: 'Raise a Ticket',
    supportOptRaiseDesc: 'Submit a support request and track it through to resolution.',
    supportOptCall: 'Call Support',
    supportOptCallDesc: 'Speak directly with a support engineer. Available 24/7.',
    supportOptWhatsApp: 'WhatsApp Support',
    supportOptWhatsAppDesc: 'Message our support team on WhatsApp for fast responses.',
    supportOptChatAction: 'Chat on WhatsApp',
    supportOptEmail: 'Email Support',
    supportOptEmailDesc: 'Send us an email and we will respond within 4 business hours.',
    slaEyebrow: 'Service Standards',
    slaHeading: 'Our SLA Commitments',
    slaSub: 'We publish our response and resolution times openly. You always know what to expect when you raise a support request.',
    slaPriority: 'Priority',
    slaDescription: 'Description',
    slaResponse: 'Response Time',
    slaResolution: 'Resolution Target',
    slaCritical: 'Critical',
    slaCriticalDesc: 'Complete system outage or security breach affecting business operations.',
    slaHigh: 'High',
    slaHighDesc: 'Major functionality impaired. Significant impact on business operations.',
    slaMedium: 'Medium',
    slaMediumDesc: 'Partial functionality impaired. Workaround available.',
    slaLow: 'Low',
    slaLowDesc: 'Minor issue or general enquiry. No significant business impact.',
    slaServiceWindow: 'Service Window',
    slaServiceWindowVal: '24 hours / 7 days a week / 365 days a year',
    slaEscalation: 'Escalation Path',
    slaEscalationVal: 'Support Engineer → Senior Engineer → Support Manager → CTO',
    csEyebrow: 'Customer Success',
    csHeading: 'We Stay With You After Go-Live',
    csBody1: 'Our Customer Success programme is an ongoing engagement — not a one-off project. From the moment your solution goes live, our team is actively working to ensure it keeps delivering value.',
    csBody2: 'This is not just reactive support. It is a proactive, structured relationship designed to protect your investment and help your technology grow with your business.',
    csProactiveTitle: 'Proactive Monitoring',
    csProactiveDesc: 'We monitor your systems continuously — identifying and resolving issues before they impact your business.',
    csDedicatedTitle: 'Dedicated Account Manager',
    csDedicatedDesc: 'Every client has a named account manager who knows your infrastructure and is your first point of contact.',
    csReviewsTitle: 'Quarterly Reviews',
    csReviewsDesc: 'We conduct regular service reviews to assess performance, plan upgrades, and align with your business goals.',
    csPartnershipTitle: 'Long-Term Partnership',
    csPartnershipDesc: 'We do not disappear after deployment. Our relationship grows with your business — for years, not months.',
    onboardEyebrow: 'Resource Hub',
    onboardHeading: 'Onboarding Resources',
    onboardSub: 'Everything you need to get up and running — guides, videos, manuals, and templates all in one place.',
    onboard1Title: 'Getting Started Guide',
    onboard1Desc: 'Step-by-step guide for new clients — from first contact to go-live.',
    onboard1Type: 'PDF Guide',
    onboard2Title: 'System Walkthrough Videos',
    onboard2Desc: 'Video tutorials covering your installed systems and how to use them.',
    onboard2Type: 'Video Series',
    onboard3Title: 'User Manuals',
    onboard3Desc: 'Detailed manuals for all hardware and software solutions deployed.',
    onboard3Type: 'Documentation',
    onboard4Title: 'Configuration Templates',
    onboard4Desc: 'Pre-built configuration templates to speed up setup and standardise deployments.',
    onboard4Type: 'Templates',
    ticketEyebrow: 'Maintenance & Support',
    ticketHeading: 'Raise a Ticket',
    ticketSub: 'Submit a support request or schedule a maintenance visit. Our team will confirm within your SLA window.',
    ticketSuccess: 'Ticket Submitted',
    ticketSuccessMsg: 'Your request has been logged. We will respond within your SLA window. Reference your email for updates.',
    faqEyebrow: 'FAQs',
    faqHeading: 'Frequently Asked Questions',
    faqOnboarding: 'Onboarding',
    faqTechnical: 'Technical',
    faqBilling: 'Billing',
    faqAccount: 'Account',
    // CSR page
    csrHeroTitle: 'Technology That Gives Back',
    csrHeroSub: 'At Proxynet, we believe technology should benefit everyone — not just those who can afford it. Our CSR programme puts that belief into action.',
    csrFocusEyebrow: 'Our Focus Areas',
    csrFocusHeading: 'Where We Make an Impact',
    csrImpactEyebrow: 'Impact Stories',
    csrImpactHeading: 'What We Have Done',
    csrPartnersEyebrow: 'Partner Organisations',
    csrPartnersHeading: 'Who We Work With',
    csrReportEyebrow: 'CSR Report',
    csrReportHeading: 'Download Our CSR Report',
    csrReportSub: 'Our annual CSR report details our initiatives, impact metrics, and commitments for the year ahead.',
    csrRequestReport: 'Request Report',
    csrGetInvolved: 'Get Involved',
    csrOutcomeLabel: 'Outcome',
    // Blog page
    blogHeroTitle: 'Technology Insights from West Africa\'s Leading ICT Company',
    blogHeroSub: 'Thought leadership, industry analysis, company news, and partner updates from the Proxynet team.',
    blogNewsletterEyebrow: 'Stay Informed',
    blogNewsletterHeading: 'Subscribe for Weekly Insights',
    blogNewsletterSub: 'Get the latest technology insights, company news, and industry analysis delivered to your inbox every week.',
    blogSubscribeSuccess: 'Thanks for subscribing! Check your inbox for a confirmation.',
    blogBackToBlog: 'Back to Blog',
    blogShareArticle: 'Share this article',
    blogAuthorBio: 'The Proxynet team shares insights from over 20 years of delivering technology solutions across West Africa.',
    blogRelatedArticles: 'Related Articles',
    articleComingSoon: 'Full Article Coming Soon',
    articleComingSoonSub: 'We are working on the full version of this article. Check back soon or subscribe to our newsletter to be notified when it goes live.',
    // Blog categories
    blogCatAll: 'All',
    blogCatTechInsights: 'Technology Insights',
    blogCatCompanyNews: 'Company News',
    blogCatPartnerUpdates: 'Partner Updates',
    blogCatIndustryFocus: 'Industry Focus',
    blogCatEdTech: 'EdTech',
    // Blog post metadata
    post1Title: 'Why Cybersecurity Is No Longer Optional for African Businesses',
    post1Excerpt: 'As digital adoption accelerates across the continent, the threat landscape is evolving fast. Here is what every business needs to know about protecting their infrastructure.',
    post2Title: 'The State of Enterprise Networking in West Africa in 2026',
    post2Excerpt: 'From SD-WAN to fibre rollouts, we break down the infrastructure trends shaping connectivity for large organisations across the region.',
    post3Title: 'Building a Disaster Recovery Plan That Actually Works',
    post3Excerpt: 'Most DR plans fail not because of bad technology, but poor planning. Our team shares the framework we use with clients across West Africa.',
    post4Title: 'Proxynet Hosts Huawei IdeaHub S3 Launch in Lagos',
    post4Excerpt: 'Proxynet Communications hosted the official Huawei IdeaHub S3 launch event at Four Points by Sheraton, Victoria Island, Lagos.',
    post5Title: 'How Smart Classrooms Are Transforming Education in Nigeria',
    post5Excerpt: 'Proxynet EdTech has deployed smart classroom solutions in schools across Lagos State. Here is what we have learned about what works.',
    post6Title: 'Proxynet Renews Samsung B2B Partnership for 2026',
    post6Excerpt: 'Proxynet Communications has renewed its Samsung B2B partnership, continuing a relationship that began over a decade ago.',
    // Hero slides
    slide0Eyebrow: 'Enterprise Technology Solutions',
    slide0Title: "Powering Africa's",
    slide0Accent: 'Digital Future',
    slide0Sub: 'World-class connectivity, infrastructure, and managed services for businesses across Africa — built for reliability, designed for growth.',

    slide1Eyebrow: 'Upcoming Event — May 6, 2026',
    slide1Title: 'Huawei IdeaHub S3',
    slide1Accent: 'Launch',
    slide1Sub: 'Experience the Future of Smart Collaboration. Join us at Four Points by Sheraton, VI, Lagos. 10:00AM WAT.',
    slide1EventDate: 'May 6, 2026',
    slide1EventTime: '10:00AM WAT',
    slide1EventVenue: 'Four Points by Sheraton, VI, Lagos',
    slide1EventCta: 'Register Now',

    slide2Eyebrow: 'Smart School Solutions',
    slide2Title: 'Empowering the Next',
    slide2Accent: 'Generation of Talent',
    slide2Sub: 'Proxynet EdTech delivers smart classrooms, digital literacy programmes, and ICT infrastructure to schools across West Africa.',

    slide3Eyebrow: 'NOC & Command Centres',
    slide3Title: 'Real-Time Monitoring',
    slide3Accent: 'at Scale',
    slide3Sub: 'From 15-display NOC solutions to full command centres — we design and deploy infrastructure that keeps your operations visible.',

    slide4Eyebrow: 'Systems Integration',
    slide4Title: 'Technology That',
    slide4Accent: 'Works Together',
    slide4Sub: 'We connect your hardware, software, and networks into one seamless system — eliminating silos and driving operational efficiency.',

    slide5Eyebrow: 'AV & Videowall Solutions',
    slide5Title: 'Displays That',
    slide5Accent: 'Command Attention',
    slide5Sub: 'From boardroom videowalls to large-scale event AV — we design, deploy, and support world-class display solutions.',

    slide6Eyebrow: 'Cybersecurity',
    slide6Title: 'Protecting Your',
    slide6Accent: 'Infrastructure',
    slide6Sub: 'Firewalls, intrusion detection, VPNs, and disaster recovery — we secure your business from threats inside and out.',
    projectsDelivered: 'Projects Delivered',
    countriesServed: 'Countries Served',
    globalPartners: 'Global Technology Partners',
  },
  fr: {
    // Nav
    getInTouch: 'Nous Contacter',
    search: 'Rechercher Proxynet…',
    home: 'Accueil',
    about: 'À Propos',
    solutions: 'Solutions',
    casestudies: 'Études de Cas',
    support: 'Assistance',
    community: 'Communauté',
    blog: 'Blog',
    connectivity: 'Connectivité',
    infrastructure: 'Infrastructure',
    managedServices: 'Services Gérés',
    internetServices: 'Services Internet',
    vsatSolutions: 'Solutions VSAT',
    dataCentre: 'Centre de Données',
    cybersecurity: 'Cybersécurité',
    itSupport: 'Support IT',
    cloudServices: 'Services Cloud',
    // Solutions (real)
    solAV: 'Solutions AV Professionnelles',
    solCybersecurity: 'Sécurité IT & Cybersécurité',
    solNetworking: 'Infrastructure Réseau & Intégration',
    solEnterpriseSoftware: 'Solutions Logicielles d\'Entreprise',
    solUnifiedComms: 'Communications Unifiées',
    solCloud: 'Cloud & Services Gérés',
    solCAD: 'Services CAO',
    solIoT: 'IoT & Infrastructure Intelligente',
    solProVMS: 'Gestion des Visiteurs — ProVMS',
    solProSkool: 'Gestion Scolaire — ProSkool',
    solERP: 'Solutions ERP',
    solDistribution: 'Distribution & Revendeurs',
    // Software
    softwareSolutions: 'Solutions Logicielles',
    customDev: 'Développement Logiciel Sur Mesure',
    webApps: 'Applications Web',
    mobileApps: 'Applications Mobiles',
    erp: 'Solutions ERP',
    // Rentals & Billboard
    rentals: 'Location d\'Équipement AV',
    rentalsDesc: 'Équipement AV de classe mondiale pour événements.',
    billboardSolutions: 'Affichage & Signalétique Numérique',
    billboardDesc: 'Déploiements de signalétique numérique intérieure et extérieure.',
    // EdTech
    edtech: 'EdTech & Écoles Intelligentes',
    edtechDesc: 'Solutions d\'écoles intelligentes, programmes d\'alphabétisation numérique et formations technologiques.',
    // Footer
    footerTagline: "Connecter l'avenir du Nigeria avec une infrastructure technologique de classe mondiale et des services gérés.",
    company: 'Entreprise',
    aboutUs: 'À Propos',
    ourTeam: 'Notre Équipe',
    careers: 'Carrières',
    newsPress: 'Actualités & Presse',
    partners: 'Partenaires',
    resources: 'Ressources',
    whitepapers: 'Livres Blancs',
    supportCentre: "Centre d'Assistance",
    faqs: 'FAQ',
    contact: 'Contact',
    stayUpdated: 'Restez informé',
    emailPlaceholder: 'Votre adresse email',
    thankYou: 'Merci pour votre inscription!',
    privacyPolicy: 'Politique de Confidentialité',
    cookiePolicy: 'Politique des Cookies',
    terms: 'Conditions Générales',
    copyright: `© ${new Date().getFullYear()} Proxynet Group Ltd. RC 472270. Tous droits réservés.`,
    // Home
    heroEyebrow: 'Solutions Technologiques d\'Entreprise',
    heroTitle: 'Propulser l\'Avenir',
    heroTitleAccent: 'Numérique de l\'Afrique',
    heroSub: 'Connectivité, infrastructure et services gérés de classe mondiale pour les entreprises à travers l\'Afrique — fiables et conçus pour la croissance.',
    exploreSolutions: 'Explorer les Solutions',
    // Final CTA
    finalCtaHeading: 'Prêt à Transformer Votre Infrastructure IT?',
    finalCtaSub: 'Parlez à notre équipe et obtenez une solution adaptée à vos besoins.',
    // Projects
    projectsEyebrow: 'Projets en Vedette',
    projectsHeading: 'Des Réalisations dont Nous Sommes Fiers',
    // Blog
    latestInsights: 'Dernières Actualités',
    viewAll: 'Voir tous les articles',
    readMore: 'Lire la suite',
    // Support CTA
    supportEyebrow: 'Succès Client',
    supportHeading: "Nous ne faisons pas que déployer, nous vous accompagnons.",
    supportSub: "Notre relation ne s'arrête pas à l'installation. Nous fournissons un support continu, une surveillance et une maintenance pour que votre technologie continue de fonctionner.",
    supportCTALabel: "Visiter notre Centre d'Assistance",
    supportPillar1: 'Surveillance et réponse aux incidents 24h/24 7j/7',
    supportPillar2: 'Ingénieurs support dédiés disponibles',
    supportPillar3: 'Partenariats à long terme, pas des projets ponctuels',
    // Industries
    industriesEyebrow: 'Secteurs que Nous Servons',
    industriesHeading: 'Conçu pour les Secteurs qui Propulsent l\'Économie Africaine',
    industriesSub: 'Nous avons livré des solutions technologiques dans de nombreux secteurs — chacun avec ses propres exigences et défis.',
    indFinancial: 'Services Financiers',
    indFinancialDesc: 'Réseaux sécurisés et infrastructure conforme pour banques et fintechs.',
    indOilGas: 'Pétrole & Gaz',
    indOilGasDesc: 'Connectivité robuste et systèmes de surveillance pour les opérations pétrolières.',
    indManufacturing: 'Industrie Manufacturière',
    indManufacturingDesc: 'Intégration de systèmes et solutions réseau pour les usines et chaînes d\'approvisionnement.',
    indTelecoms: 'Télécommunications',
    indTelecomsDesc: 'Réseaux d\'entreprise et services gérés pour les opérateurs télécoms.',
    indGovernment: 'Gouvernement',
    indGovernmentDesc: 'Infrastructure IT sécurisée et évolutive pour les agences du secteur public.',
    indEducation: 'Éducation',
    indEducationDesc: 'Réseaux de campus, salles de classe intelligentes et infrastructure e-learning.',
    indHealthcare: 'Santé',
    indHealthcareDesc: 'Connectivité fiable et sécurité des données pour hôpitaux et cliniques.',
    indRetail: 'Commerce de Détail',
    indRetailDesc: 'Affichage dynamique, réseaux PDV et infrastructure numérique pour la vente au détail.',
    // What We Do
    whatWeDoEyebrow: 'Ce Que Nous Faisons',
    whatWeDoHeading: 'Nous Construisons et Gérons l\'Infrastructure Technologique',
    whatWeDoClarity: 'Nous concevons, déployons et supportons les systèmes technologiques qui font fonctionner votre entreprise.',
    justSoYouKnow: 'Pour info',
    whatWeDoExplainer: 'Proxynet est une entreprise de solutions technologiques — pas un organisateur d\'événements. Nous aidons les entreprises africaines à construire une infrastructure IT fiable, sécuriser leurs réseaux et développer des logiciels.',
    lfdSignage: 'LFD & Affichage Dynamique',
    lfdSignageDesc: 'Systèmes d\'affichage grand format pour salles de réunion et espaces publics.',
    lfdSignageDetail: 'Nous concevons et installons des solutions d\'affichage grand format (LFD) et de signalétique numérique — des configurations de salle de réunion aux réseaux d\'affichage multi-zones.',
    systemsIntegration: 'Intégration de Systèmes',
    systemsIntegrationDesc: 'Connecter votre matériel, logiciels et réseaux en un système unifié.',
    systemsIntegrationDetail: 'Nous intégrons des systèmes technologiques disparates pour qu\'ils communiquent et fonctionnent ensemble — réduisant les processus manuels et éliminant les silos de données.',
    enterpriseSoftware: 'Développement Logiciel d\'Entreprise',
    enterpriseSoftwareDesc: 'Applications métier personnalisées construites autour de vos flux de travail.',
    enterpriseSoftwareDetail: 'Des systèmes ERP aux outils internes sur mesure, nous développons des logiciels d\'entreprise qui s\'adaptent à votre organisation.',
    enterpriseNetworking: 'Réseaux d\'Entreprise',
    enterpriseNetworkingDesc: 'Solutions LAN, MAN et WAN conçues pour la performance et la fiabilité.',
    enterpriseNetworkingDetail: 'Nous concevons et mettons en œuvre une infrastructure réseau évolutive — réseaux locaux, étendus et tout ce qui se trouve entre les deux.',
    networkSecurity: 'Sécurité Réseau',
    networkSecurityDesc: 'Protéger votre infrastructure contre les menaces internes et externes.',
    networkSecurityDetail: 'Notre équipe de sécurité met en œuvre des pare-feux, des systèmes de détection d\'intrusion, des solutions antivirus et des VPN.',
    disasterRecovery: 'Reprise après Sinistre',
    disasterRecoveryDesc: 'Garder vos données en sécurité et votre entreprise opérationnelle en cas de problème.',
    disasterRecoveryDetail: 'Nous planifions, mettons en œuvre et testons régulièrement des stratégies de reprise après sinistre pour une récupération rapide.',
    enterpriseNetworkingWan: 'Accès à Distance & VPN',
    enterpriseNetworkingWanDesc: 'Connectivité sécurisée pour les équipes travaillant de partout.',
    enterpriseNetworkingWanDetail: 'Nous mettons en œuvre des solutions d\'accès à distance et une infrastructure VPN pour une connexion sécurisée depuis n\'importe quel endroit.',
    mobileAppsDesc: 'Applications iOS et Android conçues pour les entreprises.',
    mobileAppsDetail: 'Nous développons des applications mobiles qui étendent vos capacités aux smartphones et tablettes.',
    // Industries CTAs
    findYourSolution: 'Trouver Votre Solution',
    contactSales: 'Contacter les Ventes',
    // Cookie Banner
    cookieTitle: 'Nous utilisons des cookies',
    cookieBody: 'Nous utilisons des cookies pour améliorer votre expérience, analyser le trafic et personnaliser le contenu. En cliquant sur "Accepter", vous consentez à notre utilisation des cookies conformément à notre',
    cookieAnd: 'et',
    cookieCompliance: 'Ce site est conforme au Règlement Nigérian sur la Protection des Données (NDPR) et au RGPD.',
    cookieDecline: 'Refuser',
    cookieAccept: 'Tout Accepter',
    // Testimonials / Partners placeholders
    testimonialsHeading: 'Témoignages',
    partnersHeading: 'Nos Partenaires',
    // Featured Projects CTAs
    startAProject: 'Démarrer un Projet',
    viewCaseStudies: 'Voir les Études de Cas',
    // About CTA
    readyToWorkWithUs: 'Prêt à travailler avec nous ?',
    aboutCtaSub: "Parlez à notre équipe de vos besoins technologiques — nous construirons une solution autour de votre entreprise.",
    contactUs: 'Nous Contacter',
    viewOurSolutions: 'Voir Nos Solutions',
    // Contact page
    contactNav: 'Contact',
    contactPageTitle: 'Contactez-Nous — Parlons Technologie',
    contactPageDesc: 'Contactez Proxynet Group. Rejoignez nos équipes commerciales, support, partenariats ou carrières. Bureaux à Lagos, Abuja, Accra, Abidjan et Dubaï.',
    contactHeroTitle: 'Parlons Technologie',
    contactHeroSub: 'Que vous soyez prêt à démarrer un projet, que vous ayez besoin d\'un support technique, ou que vous souhaitiez simplement explorer les possibilités — notre équipe est prête à vous aider.',
    contactCtaPrimary: 'Envoyer une Demande',
    contactCtaSecondary: 'Appelez-Nous',
    contactResponseTime: 'Nous répondons à toutes les demandes dans les 4 heures ouvrables. Les problèmes de support critiques sont traités 24h/24.',
    contactFormEyebrow: 'Envoyer un Message',
    contactFormHeading: 'Comment Pouvons-Nous Vous Aider ?',
    contactSuccessTitle: 'Demande Envoyée',
    contactSuccessMsg: 'Merci de nous avoir contactés. Notre équipe vous répondra dans les 4 heures ouvrables.',
    contactFieldName: 'Nom Complet',
    contactFieldCompany: 'Entreprise',
    contactFieldEmail: 'Adresse Email',
    contactFieldPhone: 'Numéro de Téléphone',
    contactFieldType: 'Type de Demande',
    contactFieldTypeDefault: 'Sélectionnez le type de demande',
    contactTypeSales: 'Commercial',
    contactTypeSupport: 'Support Technique',
    contactTypePartnership: 'Partenariats',
    contactTypeCareers: 'Carrières',
    contactTypeGeneral: 'Général',
    contactFieldMessage: 'Message',
    contactFieldMessagePlaceholder: 'Parlez-nous de votre projet, défi ou question…',
    contactSubmit: 'Envoyer la Demande',
    contactDirectEyebrow: 'Contacts Directs',
    contactDirectHeading: 'Rejoindre la Bonne Équipe',
    contactPhone: 'Ligne Principale',
    contactPhoneAlt: 'Ligne Secondaire',
    contactEmail: 'Email',
    contactFollowUs: 'Suivez-Nous',
    // Locations
    contactThisOffice: 'Contacter ce Bureau',
    viewOnMap: 'Voir sur la Carte',
    // Not Found
    pageNotFound: 'Page Introuvable',
    pageNotFoundSub: 'La page que vous recherchez n\'existe pas ou a été déplacée. Laissez-nous vous remettre sur la bonne voie.',
    backToHomepage: 'Retour à l\'Accueil',
    goBack: 'Retour',
    // Careers
    viewOpenRoles: 'Voir les Postes Ouverts',
    learnAboutCulture: 'Découvrir Notre Culture',
    applyForGraduate: 'Postuler au Programme Diplômé',
    applyForInternship: 'Postuler au Stage',
    apply: 'Postuler',
    submitApplication: 'Soumettre la Candidature',
    // Support
    raiseATicket: 'Soumettre un Ticket',
    callSupportNow: 'Appeler le Support',
    requestAccess: 'Demander l\'Accès',
    submitRequest: 'Soumettre la Demande',
    // Blog
    readLatestPosts: 'Lire les Derniers Articles',
    subscribeForUpdates: 'S\'abonner aux Mises à Jour',
    subscribe: 'S\'abonner',
    // EdTech
    partnerWithUs: 'Devenir Partenaire',
    viewProgrammes: 'Voir les Programmes',
    visitEdTechWebsite: 'Visiter le Site EdTech',
    submitEnquiry: 'Soumettre la Demande',
    // Billboard / Rentals
    requestAQuote: 'Demander un Devis',
    requestARental: 'Demander une Location',
    viewEquipment: 'Voir l\'Équipement',
    // Navbar solutions mega menu categories
    catAVInfra: 'AV & Infrastructure',
    catSoftwareApps: 'Logiciels & Applications',
    catManagedCloud: 'Géré & Cloud',
    catSpecialist: 'Spécialiste',
    // Featured Projects content
    proj1Solution: 'Solution NOC 15 Écrans',
    proj1Category: 'NOC & Centre de Commandement',
    proj1Outcome: 'Déploiement d\'un centre d\'opérations réseau de 15 écrans permettant une surveillance en temps réel de l\'infrastructure UBA.',
    proj2Solution: 'Videowall 4x2 46 Pouces avec Solution de Surveillance NOC',
    proj2Category: 'Videowall & NOC',
    proj2Outcome: 'Installation d\'un videowall haute résolution de 8 panneaux pour la surveillance centralisée du réseau et de la sécurité.',
    proj3Solution: 'Solution Centre de Commandement pour la Surveillance des Liens et de l\'Infrastructure',
    proj3Category: 'Conception, Déploiement & Support',
    proj3Outcome: 'Solution de centre de commandement de bout en bout pour la surveillance des liens et de l\'infrastructure sur le campus universitaire.',
    proj4Solution: 'Solution NOC 32 Écrans',
    proj4Category: 'NOC & Centre de Commandement',
    proj4Outcome: 'Déploiement d\'un centre d\'opérations réseau de 32 écrans pour Access Bank DIG, permettant une surveillance complète de l\'infrastructure.',
    proj5Solution: 'Videowall NOC avec Support de Sol Peerless',
    proj5Category: 'Videowall & NOC',
    proj5Outcome: 'Installation d\'un videowall NOC haute résolution avec support de sol Peerless au siège de FCMB Lagos.',
    proj6Solution: 'Solution Centre de Commandement pour la Surveillance de l\'Infrastructure',
    proj6Category: 'Conception, Déploiement & Support',
    proj6Outcome: 'Déploiement d\'une solution de centre de commandement pour la surveillance de l\'infrastructure dans les bureaux d\'ePROCESS à Accra, Ghana.',
    proj7Solution: 'Solution Logitech VC Multi-Sites',
    proj7Category: 'AV & Collaboration',
    proj7Outcome: 'Mise en œuvre d\'une solution de vidéoconférence Logitech multi-sites à Lagos, Bonny, Port Harcourt et Abuja.',
    // About page
    aboutUs: 'À Propos',
    aboutHeroTitle: 'Qui Nous Sommes',
    aboutHeroSub: 'Deux décennies à construire l\'infrastructure technologique qui propulse les organisations les plus ambitieuses d\'Afrique.',
    // SubNav
    subNavWhoWeAre: 'Qui Nous Sommes',
    subNavHistory: 'Histoire',
    subNavLeadership: 'Direction',
    subNavAwards: 'Récompenses',
    subNavLocations: 'Bureaux',
    // Company Overview
    overviewEyebrow: 'Qui Nous Sommes',
    overviewHeading: 'Nous ne sommes pas un fournisseur. Nous sommes votre partenaire technologique.',
    overviewBody1: 'Proxynet Group est une entreprise de solutions technologiques fondée au Nigeria en 2004. Nous concevons, déployons et supportons l\'infrastructure IT qui maintient les entreprises en activité — des réseaux d\'entreprise et la cybersécurité aux systèmes d\'affichage intelligents et aux logiciels personnalisés.',
    overviewBody2: 'Nous travaillons avec des banques, des raffineries, des agences gouvernementales, des opérateurs télécoms et des multinationales au Nigeria, au Ghana, en Côte d\'Ivoire et au-delà. Notre mission est de rendre la technologie complexe simple, fiable et durable.',
    overviewBody3: 'Nous existons parce que les entreprises africaines méritent une infrastructure technologique de classe mondiale — livrée par des personnes qui comprennent le contexte local, les défis d\'infrastructure et ce qu\'il faut pour maintenir les systèmes en fonctionnement dans cet environnement.',
    // Mission & Vision
    ourMission: 'Notre Mission',
    missionStatement: 'Atteindre et maintenir le leadership dans l\'industrie des TIC grâce à la fourniture du service de la plus haute qualité qui donnera à nos clients une valeur inégalée de manière rentable et responsable — apportant de la valeur à la communauté dans son ensemble.',
    ourVision: 'Notre Vision',
    visionStatement: 'Être une définition du vrai succès dans la livraison et le support de solutions TIC à l\'échelle mondiale — grâce à la réalisation d\'une technologie supérieure pour notre base de clients en s\'alignant constamment sur les dynamiques de l\'ère de l\'information tout en établissant et maintenant des normes.',
    // Core Values
    coreValuesEyebrow: 'Nos Valeurs',
    coreValuesSub: 'Sept principes qui guident chaque décision, chaque projet et chaque relation chez Proxynet.',
    cvPurposeTitle: 'Orienté Objectif',
    cvPurposeDesc: 'Tout ce que nous faisons est ancré dans un objectif clair — fournir une technologie qui crée une valeur réelle et durable pour nos clients et communautés.',
    cvAccountabilityTitle: 'Responsabilité',
    cvAccountabilityDesc: 'Nous assumons nos engagements. Quand nous disons que nous livrerons, nous livrons — et quand les choses tournent mal, nous les corrigeons sans excuses.',
    cvIntegrityTitle: 'Intégrité',
    cvIntegrityDesc: 'Nous faisons ce qui est juste même quand personne ne regarde. Nos clients nous confient leur infrastructure critique — nous prenons cela au sérieux.',
    cvDisciplineTitle: 'Discipline',
    cvDisciplineDesc: 'L\'excellence n\'est pas un accident. Nous suivons des processus éprouvés, maintenons des normes élevées et nous tenons à une performance constante.',
    cvStewardshipTitle: 'Intendance',
    cvStewardshipDesc: 'Nous traitons les ressources de nos clients comme les nôtres — en prenant des décisions qui protègent leurs investissements et créent de la valeur à long terme.',
    cvOnenessTitle: 'Unité',
    cvOnenessDesc: 'Nous travaillons en équipe — en interne et avec nos clients. La collaboration, pas les silos, est notre façon de résoudre des problèmes complexes.',
    cvExemplaryTitle: 'Exemplaire',
    cvExemplaryDesc: 'Nous établissons la norme. Dans notre industrie, nos communautés et notre conduite — nous visons à être l\'exemple que les autres suivent.',
    // Timeline
    timelineEyebrow: 'Notre Histoire',
    timelineHeading: 'Deux Décennies de Progrès',
    tm2004Title: 'Fondation',
    tm2004Desc: 'Proxynet Communications fondée à Lagos, Nigeria avec la mission de fournir des solutions IT de classe mondiale.',
    tm2008Title: 'Premier Grand Contrat Entreprise',
    tm2008Desc: 'Premier projet de réseau d\'entreprise à grande échelle avec une banque nigériane de premier rang.',
    tm2010Title: 'Expansion Régionale',
    tm2010Desc: 'Ouverture d\'opérations à Abuja pour servir le gouvernement fédéral et les clients du secteur public.',
    tm2012Title: 'Partenariat Samsung',
    tm2012Desc: 'Devenu partenaire Samsung B2B agréé, s\'étendant aux solutions d\'affichage grand format et de signalétique intelligente.',
    tm2014Title: 'Prix Samsung B2B',
    tm2014Desc: 'Reconnu avec le Prix Samsung B2B pour des performances exceptionnelles et la livraison client.',
    tm2016Title: 'Expansion en Afrique de l\'Ouest',
    tm2016Desc: 'Établissement d\'une présence au Ghana et en Côte d\'Ivoire, servant des clients à travers l\'Afrique de l\'Ouest.',
    tm2019Title: 'Bureau de Dubaï',
    tm2019Desc: 'Ouverture d\'un bureau au Moyen-Orient à Dubai Silicon Oasis pour servir les clients internationaux et les partenaires technologiques.',
    tm2024Title: '20 Ans de Succès',
    tm2024Desc: 'Célébration de deux décennies d\'excellence technologique — 500+ projets, 6 pays, 50+ partenaires mondiaux.',
    // Leadership
    leadershipEyebrow: 'Direction',
    leadershipHeading: 'L\'Équipe Derrière Proxynet',
    // Awards
    awardsEyebrow: 'Reconnaissance',
    awardsHeading: 'Prix & Certifications',
    awardsSub: 'Nos partenariats et accréditations reflètent la confiance que les leaders technologiques mondiaux accordent à Proxynet.',
    // Locations
    locationsEyebrow: 'Où Nous Sommes',
    locationsHeading: 'Nos Bureaux',
    locationsSub: 'De notre siège à Lagos aux bureaux à travers l\'Afrique de l\'Ouest et le Moyen-Orient — nous sommes proches des clients que nous servons.',
    // Tax Compliance
    taxTitle: 'Enregistré & Conforme aux Obligations Fiscales',
    taxBody: 'Proxynet Group Ltd est une société nigériane dûment enregistrée (RC 472270) constituée en vertu de la loi sur les sociétés et les questions connexes (CAMA). Nous sommes entièrement conformes aux obligations fiscales, détenons un numéro d\'identification fiscale valide (TIN: 00775065-0001) et déposons toutes les déclarations statutaires auprès du Service fédéral des impôts intérieurs (FIRS). Toutes les factures émises par Proxynet sont légalement valides à des fins d\'approvisionnement et d\'audit.',
    // Awards body text
    award1Body: 'Reconnu par Samsung pour des performances de vente B2B exceptionnelles et l\'excellence de la livraison client au Nigeria.',
    award2Body: 'Partenaire Samsung B2B certifié pour les écrans grand format, la signalétique intelligente et les solutions AV d\'entreprise.',
    award3Body: 'Partenaire Microsoft agréé pour les logiciels d\'entreprise, les services cloud et les solutions de licences.',
    award4Body: 'Distributeur Canon agréé pour les imprimantes, scanners, appareils photo et solutions de gestion documentaire.',
    award5Body: 'Distributeur Yealink agréé pour les téléphones IP, la vidéoconférence et les communications unifiées.',
    award6Body: 'Intégrateur système Yealink certifié pour les déploiements UC à l\'échelle de l\'entreprise et les services gérés.',
    award7Body: 'Partenaire Logitech agréé pour la collaboration vidéo, les périphériques et les solutions d\'espace de travail d\'entreprise.',
    award8Body: 'Distributeur officiel de casques professionnels et d\'appareils de communication VT en Afrique de l\'Ouest.',
    award9Body: 'Distributeur Dahua agréé pour les systèmes CCTV, caméras IP, NVR et solutions de surveillance de sécurité.',
    award10Body: 'Système de management de la qualité certifié par TNV (Cert No. SBSCKTSI20251120NGAQM10U). Valide jusqu\'au 19/11/2028.',
    // Support page
    supportHeroTitle: 'Support 24h/24, Parce que Votre Entreprise Ne S\'arrête Jamais',
    supportHeroSub: 'Notre équipe de support est disponible 24h/24 pour maintenir votre technologie opérationnelle. Soumettez un ticket, appelez-nous ou contactez-nous sur WhatsApp — nous répondons rapidement.',
    supportOptRaiseTicket: 'Soumettre un Ticket',
    supportOptRaiseDesc: 'Soumettez une demande de support et suivez-la jusqu\'à sa résolution.',
    supportOptCall: 'Appeler le Support',
    supportOptCallDesc: 'Parlez directement avec un ingénieur support. Disponible 24h/24.',
    supportOptWhatsApp: 'Support WhatsApp',
    supportOptWhatsAppDesc: 'Envoyez un message à notre équipe sur WhatsApp pour des réponses rapides.',
    supportOptChatAction: 'Discuter sur WhatsApp',
    supportOptEmail: 'Support par Email',
    supportOptEmailDesc: 'Envoyez-nous un email et nous répondrons dans les 4 heures ouvrables.',
    slaEyebrow: 'Normes de Service',
    slaHeading: 'Nos Engagements SLA',
    slaSub: 'Nous publions ouvertement nos délais de réponse et de résolution. Vous savez toujours à quoi vous attendre.',
    slaPriority: 'Priorité',
    slaDescription: 'Description',
    slaResponse: 'Délai de Réponse',
    slaResolution: 'Objectif de Résolution',
    slaCritical: 'Critique',
    slaCriticalDesc: 'Panne complète du système ou violation de sécurité affectant les opérations commerciales.',
    slaHigh: 'Élevée',
    slaHighDesc: 'Fonctionnalité majeure altérée. Impact significatif sur les opérations commerciales.',
    slaMedium: 'Moyenne',
    slaMediumDesc: 'Fonctionnalité partielle altérée. Solution de contournement disponible.',
    slaLow: 'Faible',
    slaLowDesc: 'Problème mineur ou demande générale. Aucun impact commercial significatif.',
    slaServiceWindow: 'Fenêtre de Service',
    slaServiceWindowVal: '24 heures / 7 jours par semaine / 365 jours par an',
    slaEscalation: 'Chemin d\'Escalade',
    slaEscalationVal: 'Ingénieur Support → Ingénieur Senior → Responsable Support → CTO',
    csEyebrow: 'Succès Client',
    csHeading: 'Nous Restons avec Vous Après le Lancement',
    csBody1: 'Notre programme de Succès Client est un engagement continu — pas un projet ponctuel. Dès que votre solution est en ligne, notre équipe travaille activement pour s\'assurer qu\'elle continue à créer de la valeur.',
    csBody2: 'Ce n\'est pas seulement un support réactif. C\'est une relation proactive et structurée conçue pour protéger votre investissement et aider votre technologie à évoluer avec votre entreprise.',
    csProactiveTitle: 'Surveillance Proactive',
    csProactiveDesc: 'Nous surveillons vos systèmes en continu — identifiant et résolvant les problèmes avant qu\'ils n\'impactent votre entreprise.',
    csDedicatedTitle: 'Responsable de Compte Dédié',
    csDedicatedDesc: 'Chaque client a un responsable de compte nommé qui connaît votre infrastructure et est votre premier point de contact.',
    csReviewsTitle: 'Revues Trimestrielles',
    csReviewsDesc: 'Nous effectuons des revues de service régulières pour évaluer les performances, planifier les mises à niveau et s\'aligner sur vos objectifs.',
    csPartnershipTitle: 'Partenariat à Long Terme',
    csPartnershipDesc: 'Nous ne disparaissons pas après le déploiement. Notre relation grandit avec votre entreprise — pour des années, pas des mois.',
    onboardEyebrow: 'Centre de Ressources',
    onboardHeading: 'Ressources d\'Intégration',
    onboardSub: 'Tout ce dont vous avez besoin pour démarrer — guides, vidéos, manuels et modèles en un seul endroit.',
    onboard1Title: 'Guide de Démarrage',
    onboard1Desc: 'Guide étape par étape pour les nouveaux clients — du premier contact au lancement.',
    onboard1Type: 'Guide PDF',
    onboard2Title: 'Vidéos de Présentation du Système',
    onboard2Desc: 'Tutoriels vidéo couvrant vos systèmes installés et comment les utiliser.',
    onboard2Type: 'Série Vidéo',
    onboard3Title: 'Manuels Utilisateur',
    onboard3Desc: 'Manuels détaillés pour toutes les solutions matérielles et logicielles déployées.',
    onboard3Type: 'Documentation',
    onboard4Title: 'Modèles de Configuration',
    onboard4Desc: 'Modèles de configuration prédéfinis pour accélérer la configuration et standardiser les déploiements.',
    onboard4Type: 'Modèles',
    ticketEyebrow: 'Maintenance & Support',
    ticketHeading: 'Soumettre un Ticket',
    ticketSub: 'Soumettez une demande de support ou planifiez une visite de maintenance. Notre équipe confirmera dans votre fenêtre SLA.',
    ticketSuccess: 'Ticket Soumis',
    ticketSuccessMsg: 'Votre demande a été enregistrée. Nous répondrons dans votre fenêtre SLA. Référencez votre email pour les mises à jour.',
    faqEyebrow: 'FAQ',
    faqHeading: 'Questions Fréquemment Posées',
    faqOnboarding: 'Intégration',
    faqTechnical: 'Technique',
    faqBilling: 'Facturation',
    faqAccount: 'Compte',
    // CSR page
    csrHeroTitle: 'Une Technologie Qui Redonne',
    csrHeroSub: 'Chez Proxynet, nous croyons que la technologie devrait bénéficier à tous — pas seulement à ceux qui peuvent se le permettre. Notre programme RSE met cette conviction en action.',
    csrFocusEyebrow: 'Nos Domaines d\'Action',
    csrFocusHeading: 'Où Nous Avons un Impact',
    csrImpactEyebrow: 'Histoires d\'Impact',
    csrImpactHeading: 'Ce Que Nous Avons Accompli',
    csrPartnersEyebrow: 'Organisations Partenaires',
    csrPartnersHeading: 'Avec Qui Nous Travaillons',
    csrReportEyebrow: 'Rapport RSE',
    csrReportHeading: 'Télécharger Notre Rapport RSE',
    csrReportSub: 'Notre rapport RSE annuel détaille nos initiatives, nos indicateurs d\'impact et nos engagements pour l\'année à venir.',
    csrRequestReport: 'Demander le Rapport',
    csrGetInvolved: 'S\'Impliquer',
    csrOutcomeLabel: 'Résultat',
    // Blog page
    blogHeroTitle: 'Perspectives Technologiques de la Principale Entreprise TIC d\'Afrique de l\'Ouest',
    blogHeroSub: 'Leadership éclairé, analyse sectorielle, actualités de l\'entreprise et mises à jour des partenaires de l\'équipe Proxynet.',
    blogNewsletterEyebrow: 'Restez Informé',
    blogNewsletterHeading: 'Abonnez-vous pour des Insights Hebdomadaires',
    blogNewsletterSub: 'Recevez les dernières perspectives technologiques, actualités de l\'entreprise et analyses sectorielles dans votre boîte de réception chaque semaine.',
    blogSubscribeSuccess: 'Merci pour votre abonnement ! Vérifiez votre boîte de réception pour une confirmation.',
    blogBackToBlog: 'Retour au Blog',
    blogShareArticle: 'Partager cet article',
    blogAuthorBio: 'L\'équipe Proxynet partage des perspectives issues de plus de 20 ans de livraison de solutions technologiques en Afrique de l\'Ouest.',
    blogRelatedArticles: 'Articles Connexes',
    articleComingSoon: 'Article Complet Bientôt Disponible',
    articleComingSoonSub: 'Nous travaillons sur la version complète de cet article. Revenez bientôt ou abonnez-vous à notre newsletter pour être notifié lors de sa publication.',
    blogReadMore: 'Lire la suite',
    // Blog categories
    blogCatAll: 'Tout',
    blogCatTechInsights: 'Perspectives Technologiques',
    blogCatCompanyNews: 'Actualités de l\'Entreprise',
    blogCatPartnerUpdates: 'Mises à Jour Partenaires',
    blogCatIndustryFocus: 'Focus Sectoriel',
    blogCatEdTech: 'EdTech',
    // Blog post metadata
    post1Title: 'Pourquoi la Cybersécurité N\'est Plus Optionnelle pour les Entreprises Africaines',
    post1Excerpt: 'Alors que l\'adoption numérique s\'accélère sur le continent, le paysage des menaces évolue rapidement. Voici ce que chaque entreprise doit savoir pour protéger son infrastructure.',
    post2Title: 'L\'État des Réseaux d\'Entreprise en Afrique de l\'Ouest en 2026',
    post2Excerpt: 'Du SD-WAN aux déploiements de fibre, nous analysons les tendances d\'infrastructure qui façonnent la connectivité des grandes organisations dans la région.',
    post3Title: 'Construire un Plan de Reprise après Sinistre qui Fonctionne Vraiment',
    post3Excerpt: 'La plupart des plans de reprise échouent non pas à cause d\'une mauvaise technologie, mais d\'une mauvaise planification. Notre équipe partage le cadre que nous utilisons avec nos clients.',
    post4Title: 'Proxynet Organise le Lancement du Huawei IdeaHub S3 à Lagos',
    post4Excerpt: 'Proxynet Communications a organisé le lancement officiel du Huawei IdeaHub S3 au Four Points by Sheraton, Victoria Island, Lagos.',
    post5Title: 'Comment les Salles de Classe Intelligentes Transforment l\'Éducation au Nigeria',
    post5Excerpt: 'Proxynet EdTech a déployé des solutions de salles de classe intelligentes dans des écoles de l\'État de Lagos. Voici ce que nous avons appris sur ce qui fonctionne.',
    post6Title: 'Proxynet Renouvelle son Partenariat Samsung B2B pour 2026',
    post6Excerpt: 'Proxynet Communications a renouvelé son partenariat Samsung B2B, poursuivant une relation qui a débuté il y a plus d\'une décennie.',
    slide0Eyebrow: 'Solutions Technologiques d\'Entreprise',
    slide0Title: 'Propulser l\'Avenir',
    slide0Accent: 'Numérique de l\'Afrique',
    slide0Sub: 'Connectivité, infrastructure et services gérés de classe mondiale pour les entreprises à travers l\'Afrique — fiables et conçus pour la croissance.',

    slide1Eyebrow: 'Événement à Venir — 6 Mai 2026',
    slide1Title: 'Huawei IdeaHub S3',
    slide1Accent: 'Lancement',
    slide1Sub: 'Découvrez l\'Avenir de la Collaboration Intelligente. Rejoignez-nous au Four Points by Sheraton, VI, Lagos. 10h00 WAT.',
    slide1EventDate: '6 Mai 2026',
    slide1EventTime: '10h00 WAT',
    slide1EventVenue: 'Four Points by Sheraton, VI, Lagos',
    slide1EventCta: 'S\'inscrire',

    slide2Eyebrow: 'Solutions pour Écoles Intelligentes',
    slide2Title: 'Former la Prochaine',
    slide2Accent: 'Génération de Talents',
    slide2Sub: 'Proxynet EdTech déploie des salles de classe intelligentes, des programmes d\'alphabétisation numérique et des infrastructures TIC dans les écoles d\'Afrique de l\'Ouest.',

    slide3Eyebrow: 'NOC & Centres de Commandement',
    slide3Title: 'Surveillance en Temps Réel',
    slide3Accent: 'à Grande Échelle',
    slide3Sub: 'Des solutions NOC à 15 écrans aux centres de commandement complets — nous concevons et déployons l\'infrastructure qui garde vos opérations visibles.',

    slide4Eyebrow: 'Intégration de Systèmes',
    slide4Title: 'Une Technologie Qui',
    slide4Accent: 'Fonctionne Ensemble',
    slide4Sub: 'Nous connectons votre matériel, vos logiciels et vos réseaux en un système unifié — éliminant les silos et améliorant l\'efficacité opérationnelle.',

    slide5Eyebrow: 'Solutions AV & Videowalls',
    slide5Title: 'Des Écrans Qui',
    slide5Accent: 'Captent l\'Attention',
    slide5Sub: 'Des videowalls de salle de réunion aux événements AV à grande échelle — nous concevons, déployons et supportons des solutions d\'affichage de classe mondiale.',

    slide6Eyebrow: 'Cybersécurité',
    slide6Title: 'Protéger Votre',
    slide6Accent: 'Infrastructure',
    slide6Sub: 'Pare-feux, détection d\'intrusion, VPN et reprise après sinistre — nous sécurisons votre entreprise contre les menaces internes et externes.',
    projectsDelivered: 'Projets Réalisés',
    countriesServed: 'Pays Desservis',
    globalPartners: 'Partenaires Technologiques Mondiaux',
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = translations[lang]
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
