import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const translations = {
  en: {
    // Nav
    getInTouch: 'Get in Touch',
    search: 'Search Proxynet…',
    home: 'Home',
    about: 'About',
    solutions: 'Solutions',
    casestudies: 'Case Studies',
    support: 'Support',
    community: 'Community',
    blog: 'Blog',
    connectivity: 'Connectivity',
    infrastructure: 'Infrastructure',
    managedServices: 'Managed Services',
    internetServices: 'Internet Services',
    vsatSolutions: 'VSAT Solutions',
    dataCentre: 'Data Centre',
    cybersecurity: 'Cybersecurity',
    itSupport: 'IT Support',
    cloudServices: 'Cloud Services',
    // Solutions (real)
    solAV: 'Professional AV Solutions',
    solCybersecurity: 'IT Security & Cybersecurity',
    solNetworking: 'Network Infrastructure & Systems Integration',
    solEnterpriseSoftware: 'Enterprise Software Solutions',
    solUnifiedComms: 'Unified Communications',
    solCloud: 'Cloud & Managed Services',
    solCAD: 'CAD Services',
    solIoT: 'IoT & Smart Infrastructure',
    solProVMS: 'Visitor Management — ProVMS',
    solProSkool: 'School Management — ProSkool',
    solERP: 'ERP Solutions',
    solDistribution: 'Distribution & Reseller Services',
    // Software
    softwareSolutions: 'Software Solutions',
    customDev: 'Custom Software Development',
    webApps: 'Web Applications',
    mobileApps: 'Mobile Applications',
    erp: 'ERP Solutions',
    // Rentals & Billboard
    rentals: 'AV Equipment Rentals',
    rentalsDesc: 'World-class AV equipment for events and activations.',
    billboardSolutions: 'Billboard & Digital Signage',
    billboardDesc: 'Indoor and outdoor digital signage and LED wall deployments.',
    // EdTech
    edtech: 'EdTech & Smart Schools',
    edtechDesc: 'Smart school solutions, digital literacy programmes, and technology training.',
    // Footer
    footerTagline: "Connecting Nigeria's future with world-class technology infrastructure and managed services.",
    company: 'Company',
    aboutUs: 'About Us',
    ourTeam: 'Our Team',
    careers: 'Careers',
    newsPress: 'News & Press',
    partners: 'Partners',
    resources: 'Resources',
    whitepapers: 'Whitepapers',
    supportCentre: 'Support Centre',
    faqs: 'FAQs',
    contact: 'Contact',
    stayUpdated: 'Stay updated',
    emailPlaceholder: 'Your email address',
    thankYou: 'Thanks for subscribing!',
    privacyPolicy: 'Privacy Policy',
    cookiePolicy: 'Cookie Policy',
    terms: 'Terms & Conditions',
    copyright: `© ${new Date().getFullYear()} Proxynet Group Ltd. RC 472270. All rights reserved.`,
    // Home
    heroEyebrow: 'Enterprise Technology Solutions',
    heroTitle: 'Powering Africa\'s',
    heroTitleAccent: 'Digital Future',
    heroSub: 'World-class connectivity, infrastructure, and managed services for businesses across Africa — built for reliability, designed for growth.',
    exploreSolutions: 'Explore Solutions',
    // Final CTA
    finalCtaHeading: 'Ready to Transform Your IT Infrastructure?',
    finalCtaSub: 'Talk to our team and get a solution tailored to your business needs.',
    // Projects
    projectsEyebrow: 'Featured Projects',
    projectsHeading: 'Work We\'re Proud Of',
    // Blog
    latestInsights: 'Latest Insights',
    viewAll: 'View all posts',
    readMore: 'Read more',
    // Support CTA
    supportEyebrow: 'Customer Success',
    supportHeading: "We don't just deploy, we support you.",
    supportSub: "Our relationship doesn't end at installation. We provide ongoing support, monitoring, and maintenance to ensure your technology keeps working — long after the project is delivered.",
    supportCTALabel: 'Visit our Support Centre',
    supportPillar1: '24/7 monitoring and incident response',
    supportPillar2: 'Dedicated support engineers on call',
    supportPillar3: 'Long-term partnerships, not one-off projects',
    // Industries
    industriesEyebrow: 'Industries We Serve',
    industriesHeading: 'Built for the Sectors That Drive Africa\'s Economy',
    industriesSub: 'We\'ve delivered technology solutions across a wide range of industries — each with its own demands, regulations, and infrastructure challenges.',
    indFinancial: 'Financial Services',
    indFinancialDesc: 'Secure networks and compliance-ready infrastructure for banks and fintechs.',
    indOilGas: 'Oil & Gas',
    indOilGasDesc: 'Rugged connectivity and monitoring systems for upstream and downstream operations.',
    indManufacturing: 'Manufacturing',
    indManufacturingDesc: 'Systems integration and network solutions for factory floors and supply chains.',
    indTelecoms: 'Telecoms',
    indTelecomsDesc: 'Enterprise networking and managed services for telecoms operators.',
    indGovernment: 'Government',
    indGovernmentDesc: 'Secure, scalable IT infrastructure for public sector agencies and ministries.',
    indEducation: 'Education',
    indEducationDesc: 'Campus networks, smart classrooms, and e-learning infrastructure.',
    indHealthcare: 'Healthcare',
    indHealthcareDesc: 'Reliable connectivity and data security for hospitals and clinics.',
    indRetail: 'Retail',
    indRetailDesc: 'Smart signage, POS networks, and digital infrastructure for retail environments.',
    // What We Do
    whatWeDoEyebrow: 'What We Do',
    whatWeDoHeading: 'We Build & Manage Technology Infrastructure',
    whatWeDoClarity: 'We design, deploy, and support the technology systems that keep your business running — from networks and security to software and smart displays.',
    justSoYouKnow: 'Just so you know',
    whatWeDoExplainer: 'Proxynet is a technology solutions company — not an events organiser. We help businesses across Africa build reliable IT infrastructure, secure their networks, and develop software. If you\'ve heard otherwise, we\'re glad you\'re here to find out what we actually do.',
    lfdSignage: 'LFD & Smart Signage',
    lfdSignageDesc: 'Large format display systems for boardrooms, lobbies, and public spaces.',
    lfdSignageDetail: 'We design and install large format display (LFD) and smart signage solutions — from single-screen boardroom setups to multi-zone digital signage networks across campuses and retail environments.',
    systemsIntegration: 'Systems Integration',
    systemsIntegrationDesc: 'Connecting your hardware, software, and networks into one seamless system.',
    systemsIntegrationDetail: 'We integrate disparate technology systems so they communicate and work together — reducing manual processes, eliminating data silos, and giving your team a unified view of operations.',
    enterpriseSoftware: 'Enterprise Software Development',
    enterpriseSoftwareDesc: 'Custom business applications built around your workflows.',
    enterpriseSoftwareDetail: 'From ERP systems to bespoke internal tools, we develop enterprise software that fits how your organisation actually works — not the other way around.',
    enterpriseNetworking: 'Enterprise Networking',
    enterpriseNetworkingDesc: 'LAN, MAN, and WAN solutions designed for performance and reliability.',
    enterpriseNetworkingDetail: 'We design and implement scalable network infrastructure — local area networks, wide area networks, and everything in between — built to handle your current load and grow with you.',
    networkSecurity: 'Network Security',
    networkSecurityDesc: 'Protecting your infrastructure from threats, inside and out.',
    networkSecurityDetail: 'Our security team implements firewalls, intrusion detection systems, anti-virus solutions, and VPNs to protect your organisation from both external attacks and internal vulnerabilities.',
    disasterRecovery: 'Disaster Recovery',
    disasterRecoveryDesc: 'Keeping your data safe and your business running when things go wrong.',
    disasterRecoveryDetail: 'We plan, implement, and regularly test disaster recovery strategies so that when the unexpected happens — hardware failure, cyberattack, or natural disaster — your business recovers fast.',
    enterpriseNetworkingWan: 'Remote Access & VPN',
    enterpriseNetworkingWanDesc: 'Secure connectivity for teams working from anywhere.',
    enterpriseNetworkingWanDetail: 'We implement remote access solutions and VPN infrastructure that let your team connect securely to company systems from any location, without compromising security.',
    mobileAppsDesc: 'iOS and Android applications built for business.',
    mobileAppsDetail: 'We build mobile applications that extend your business capabilities to smartphones and tablets — whether customer-facing apps or internal tools for field teams.',
    // Industries CTAs
    findYourSolution: 'Find Your Solution',
    contactSales: 'Contact Sales',
    // Cookie Banner
    cookieTitle: 'We use cookies',
    cookieBody: 'We use cookies to improve your experience on our website, analyse traffic, and personalise content. By clicking "Accept", you consent to our use of cookies in accordance with our',
    cookieAnd: 'and',
    cookieCompliance: 'This site complies with the Nigeria Data Protection Regulation (NDPR) and GDPR.',
    cookieDecline: 'Decline',
    cookieAccept: 'Accept All',
    // Testimonials / Partners placeholders
    testimonialsHeading: 'Testimonials',
    partnersHeading: 'Our Partners',
    // Featured Projects CTAs
    startAProject: 'Start a Project',
    viewCaseStudies: 'View Case Studies',
    // About CTA
    readyToWorkWithUs: 'Ready to work with us?',
    aboutCtaSub: "Talk to our team about your technology needs — we'll build a solution around your business.",
    contactUs: 'Contact Us',
    viewOurSolutions: 'View Our Solutions',
    // Locations
    contactThisOffice: 'Contact This Office',
    viewOnMap: 'View on Map',
    // Not Found
    pageNotFound: 'Page Not Found',
    pageNotFoundSub: 'The page you are looking for does not exist or has been moved. Let us get you back on track.',
    backToHomepage: 'Back to Homepage',
    goBack: 'Go Back',
    // Careers
    viewOpenRoles: 'View Open Roles',
    learnAboutCulture: 'Learn About Our Culture',
    applyForGraduate: 'Apply for Graduate Programme',
    applyForInternship: 'Apply for Internship',
    apply: 'Apply',
    submitApplication: 'Submit Application',
    // Support
    raiseATicket: 'Raise a Ticket',
    callSupportNow: 'Call Support Now',
    requestAccess: 'Request Access',
    submitRequest: 'Submit Request',
    // Blog
    readLatestPosts: 'Read Latest Posts',
    subscribeForUpdates: 'Subscribe for Updates',
    subscribe: 'Subscribe',
    // EdTech
    partnerWithUs: 'Partner With Us',
    viewProgrammes: 'View Programmes',
    visitEdTechWebsite: 'Visit the EdTech Website',
    submitEnquiry: 'Submit Enquiry',
    // Billboard / Rentals
    requestAQuote: 'Request a Quote',
    requestARental: 'Request a Rental',
    viewEquipment: 'View Equipment',
    // Navbar solutions mega menu categories
    catAVInfra: 'AV & Infrastructure',
    catSoftwareApps: 'Software & Apps',
    catManagedCloud: 'Managed & Cloud',
    catSpecialist: 'Specialist',
    // Featured Projects content
    proj1Solution: '15-Display NOC Solution',
    proj1Category: 'NOC & Command Centre',
    proj1Outcome: 'Deployed a 15-screen network operations centre enabling real-time monitoring across UBA infrastructure.',
    proj2Solution: '4x2 46-Inch Videowall with NOC Monitoring Solution',
    proj2Category: 'Videowall & NOC',
    proj2Outcome: 'Installed a high-resolution 8-panel videowall for centralised network and security monitoring.',
    proj3Solution: 'Command Center Solution for Link Health and Infrastructure Monitoring',
    proj3Category: 'Design, Deployment & Support',
    proj3Outcome: 'End-to-end command center solution for monitoring link health and infrastructure across the university campus.',
    proj4Solution: '32-Display NOC Solution',
    proj4Category: 'NOC & Command Centre',
    proj4Outcome: 'Deployed a 32-screen network operations centre for Access Bank DIG, enabling comprehensive infrastructure monitoring.',
    proj5Solution: 'NOC VideoWall with Peerless VideoWall Floor Stand',
    proj5Category: 'Videowall & NOC',
    proj5Outcome: 'Installed a high-resolution NOC videowall with Peerless floor stand at FCMB Lagos headquarters.',
    proj6Solution: 'Command Center Solution for Infrastructure Monitoring',
    proj6Category: 'Design, Deployment & Support',
    proj6Outcome: 'Deployed a command center solution for infrastructure monitoring at ePROCESS offices in Accra, Ghana.',
    proj7Solution: 'Multi-Site Logitech VC Solution',
    proj7Category: 'AV & Collaboration',
    proj7Outcome: 'Implemented a multi-site Logitech video conferencing solution across Lagos, Bonny, Port Harcourt, and Abuja.',
    // Hero slides
    slide0Eyebrow: 'Enterprise Technology Solutions',
    slide0Title: "Powering Africa's",
    slide0Accent: 'Digital Future',
    slide0Sub: 'World-class connectivity, infrastructure, and managed services for businesses across Africa — built for reliability, designed for growth.',

    slide1Eyebrow: 'Upcoming Event — May 6, 2026',
    slide1Title: 'Huawei IdeaHub S3',
    slide1Accent: 'Launch',
    slide1Sub: 'Experience the Future of Smart Collaboration. Join us at Four Points by Sheraton, VI, Lagos. 10:00AM WAT.',
    slide1EventDate: 'May 6, 2026',
    slide1EventTime: '10:00AM WAT',
    slide1EventVenue: 'Four Points by Sheraton, VI, Lagos',
    slide1EventCta: 'Register Now',

    slide2Eyebrow: 'Smart School Solutions',
    slide2Title: 'Empowering the Next',
    slide2Accent: 'Generation of Talent',
    slide2Sub: 'Proxynet EdTech delivers smart classrooms, digital literacy programmes, and ICT infrastructure to schools across West Africa.',

    slide3Eyebrow: 'NOC & Command Centres',
    slide3Title: 'Real-Time Monitoring',
    slide3Accent: 'at Scale',
    slide3Sub: 'From 15-display NOC solutions to full command centres — we design and deploy infrastructure that keeps your operations visible.',

    slide4Eyebrow: 'Systems Integration',
    slide4Title: 'Technology That',
    slide4Accent: 'Works Together',
    slide4Sub: 'We connect your hardware, software, and networks into one seamless system — eliminating silos and driving operational efficiency.',

    slide5Eyebrow: 'AV & Videowall Solutions',
    slide5Title: 'Displays That',
    slide5Accent: 'Command Attention',
    slide5Sub: 'From boardroom videowalls to large-scale event AV — we design, deploy, and support world-class display solutions.',

    slide6Eyebrow: 'Cybersecurity',
    slide6Title: 'Protecting Your',
    slide6Accent: 'Infrastructure',
    slide6Sub: 'Firewalls, intrusion detection, VPNs, and disaster recovery — we secure your business from threats inside and out.',
    projectsDelivered: 'Projects Delivered',
    countriesServed: 'Countries Served',
    globalPartners: 'Global Technology Partners',
  },
  fr: {
    // Nav
    getInTouch: 'Nous Contacter',
    search: 'Rechercher Proxynet…',
    home: 'Accueil',
    about: 'À Propos',
    solutions: 'Solutions',
    casestudies: 'Études de Cas',
    support: 'Assistance',
    community: 'Communauté',
    blog: 'Blog',
    connectivity: 'Connectivité',
    infrastructure: 'Infrastructure',
    managedServices: 'Services Gérés',
    internetServices: 'Services Internet',
    vsatSolutions: 'Solutions VSAT',
    dataCentre: 'Centre de Données',
    cybersecurity: 'Cybersécurité',
    itSupport: 'Support IT',
    cloudServices: 'Services Cloud',
    // Solutions (real)
    solAV: 'Solutions AV Professionnelles',
    solCybersecurity: 'Sécurité IT & Cybersécurité',
    solNetworking: 'Infrastructure Réseau & Intégration',
    solEnterpriseSoftware: 'Solutions Logicielles d\'Entreprise',
    solUnifiedComms: 'Communications Unifiées',
    solCloud: 'Cloud & Services Gérés',
    solCAD: 'Services CAO',
    solIoT: 'IoT & Infrastructure Intelligente',
    solProVMS: 'Gestion des Visiteurs — ProVMS',
    solProSkool: 'Gestion Scolaire — ProSkool',
    solERP: 'Solutions ERP',
    solDistribution: 'Distribution & Revendeurs',
    // Software
    softwareSolutions: 'Solutions Logicielles',
    customDev: 'Développement Logiciel Sur Mesure',
    webApps: 'Applications Web',
    mobileApps: 'Applications Mobiles',
    erp: 'Solutions ERP',
    // Rentals & Billboard
    rentals: 'Location d\'Équipement AV',
    rentalsDesc: 'Équipement AV de classe mondiale pour événements.',
    billboardSolutions: 'Affichage & Signalétique Numérique',
    billboardDesc: 'Déploiements de signalétique numérique intérieure et extérieure.',
    // EdTech
    edtech: 'EdTech & Écoles Intelligentes',
    edtechDesc: 'Solutions d\'écoles intelligentes, programmes d\'alphabétisation numérique et formations technologiques.',
    // Footer
    footerTagline: "Connecter l'avenir du Nigeria avec une infrastructure technologique de classe mondiale et des services gérés.",
    company: 'Entreprise',
    aboutUs: 'À Propos',
    ourTeam: 'Notre Équipe',
    careers: 'Carrières',
    newsPress: 'Actualités & Presse',
    partners: 'Partenaires',
    resources: 'Ressources',
    whitepapers: 'Livres Blancs',
    supportCentre: "Centre d'Assistance",
    faqs: 'FAQ',
    contact: 'Contact',
    stayUpdated: 'Restez informé',
    emailPlaceholder: 'Votre adresse email',
    thankYou: 'Merci pour votre inscription!',
    privacyPolicy: 'Politique de Confidentialité',
    cookiePolicy: 'Politique des Cookies',
    terms: 'Conditions Générales',
    copyright: `© ${new Date().getFullYear()} Proxynet Group Ltd. RC 472270. Tous droits réservés.`,
    // Home
    heroEyebrow: 'Solutions Technologiques d\'Entreprise',
    heroTitle: 'Propulser l\'Avenir',
    heroTitleAccent: 'Numérique de l\'Afrique',
    heroSub: 'Connectivité, infrastructure et services gérés de classe mondiale pour les entreprises à travers l\'Afrique — fiables et conçus pour la croissance.',
    exploreSolutions: 'Explorer les Solutions',
    // Final CTA
    finalCtaHeading: 'Prêt à Transformer Votre Infrastructure IT?',
    finalCtaSub: 'Parlez à notre équipe et obtenez une solution adaptée à vos besoins.',
    // Projects
    projectsEyebrow: 'Projets en Vedette',
    projectsHeading: 'Des Réalisations dont Nous Sommes Fiers',
    // Blog
    latestInsights: 'Dernières Actualités',
    viewAll: 'Voir tous les articles',
    readMore: 'Lire la suite',
    // Support CTA
    supportEyebrow: 'Succès Client',
    supportHeading: "Nous ne faisons pas que déployer, nous vous accompagnons.",
    supportSub: "Notre relation ne s'arrête pas à l'installation. Nous fournissons un support continu, une surveillance et une maintenance pour que votre technologie continue de fonctionner.",
    supportCTALabel: "Visiter notre Centre d'Assistance",
    supportPillar1: 'Surveillance et réponse aux incidents 24h/24 7j/7',
    supportPillar2: 'Ingénieurs support dédiés disponibles',
    supportPillar3: 'Partenariats à long terme, pas des projets ponctuels',
    // Industries
    industriesEyebrow: 'Secteurs que Nous Servons',
    industriesHeading: 'Conçu pour les Secteurs qui Propulsent l\'Économie Africaine',
    industriesSub: 'Nous avons livré des solutions technologiques dans de nombreux secteurs — chacun avec ses propres exigences et défis.',
    indFinancial: 'Services Financiers',
    indFinancialDesc: 'Réseaux sécurisés et infrastructure conforme pour banques et fintechs.',
    indOilGas: 'Pétrole & Gaz',
    indOilGasDesc: 'Connectivité robuste et systèmes de surveillance pour les opérations pétrolières.',
    indManufacturing: 'Industrie Manufacturière',
    indManufacturingDesc: 'Intégration de systèmes et solutions réseau pour les usines et chaînes d\'approvisionnement.',
    indTelecoms: 'Télécommunications',
    indTelecomsDesc: 'Réseaux d\'entreprise et services gérés pour les opérateurs télécoms.',
    indGovernment: 'Gouvernement',
    indGovernmentDesc: 'Infrastructure IT sécurisée et évolutive pour les agences du secteur public.',
    indEducation: 'Éducation',
    indEducationDesc: 'Réseaux de campus, salles de classe intelligentes et infrastructure e-learning.',
    indHealthcare: 'Santé',
    indHealthcareDesc: 'Connectivité fiable et sécurité des données pour hôpitaux et cliniques.',
    indRetail: 'Commerce de Détail',
    indRetailDesc: 'Affichage dynamique, réseaux PDV et infrastructure numérique pour la vente au détail.',
    // What We Do
    whatWeDoEyebrow: 'Ce Que Nous Faisons',
    whatWeDoHeading: 'Nous Construisons et Gérons l\'Infrastructure Technologique',
    whatWeDoClarity: 'Nous concevons, déployons et supportons les systèmes technologiques qui font fonctionner votre entreprise.',
    justSoYouKnow: 'Pour info',
    whatWeDoExplainer: 'Proxynet est une entreprise de solutions technologiques — pas un organisateur d\'événements. Nous aidons les entreprises africaines à construire une infrastructure IT fiable, sécuriser leurs réseaux et développer des logiciels.',
    lfdSignage: 'LFD & Affichage Dynamique',
    lfdSignageDesc: 'Systèmes d\'affichage grand format pour salles de réunion et espaces publics.',
    lfdSignageDetail: 'Nous concevons et installons des solutions d\'affichage grand format (LFD) et de signalétique numérique — des configurations de salle de réunion aux réseaux d\'affichage multi-zones.',
    systemsIntegration: 'Intégration de Systèmes',
    systemsIntegrationDesc: 'Connecter votre matériel, logiciels et réseaux en un système unifié.',
    systemsIntegrationDetail: 'Nous intégrons des systèmes technologiques disparates pour qu\'ils communiquent et fonctionnent ensemble — réduisant les processus manuels et éliminant les silos de données.',
    enterpriseSoftware: 'Développement Logiciel d\'Entreprise',
    enterpriseSoftwareDesc: 'Applications métier personnalisées construites autour de vos flux de travail.',
    enterpriseSoftwareDetail: 'Des systèmes ERP aux outils internes sur mesure, nous développons des logiciels d\'entreprise qui s\'adaptent à votre organisation.',
    enterpriseNetworking: 'Réseaux d\'Entreprise',
    enterpriseNetworkingDesc: 'Solutions LAN, MAN et WAN conçues pour la performance et la fiabilité.',
    enterpriseNetworkingDetail: 'Nous concevons et mettons en œuvre une infrastructure réseau évolutive — réseaux locaux, étendus et tout ce qui se trouve entre les deux.',
    networkSecurity: 'Sécurité Réseau',
    networkSecurityDesc: 'Protéger votre infrastructure contre les menaces internes et externes.',
    networkSecurityDetail: 'Notre équipe de sécurité met en œuvre des pare-feux, des systèmes de détection d\'intrusion, des solutions antivirus et des VPN.',
    disasterRecovery: 'Reprise après Sinistre',
    disasterRecoveryDesc: 'Garder vos données en sécurité et votre entreprise opérationnelle en cas de problème.',
    disasterRecoveryDetail: 'Nous planifions, mettons en œuvre et testons régulièrement des stratégies de reprise après sinistre pour une récupération rapide.',
    enterpriseNetworkingWan: 'Accès à Distance & VPN',
    enterpriseNetworkingWanDesc: 'Connectivité sécurisée pour les équipes travaillant de partout.',
    enterpriseNetworkingWanDetail: 'Nous mettons en œuvre des solutions d\'accès à distance et une infrastructure VPN pour une connexion sécurisée depuis n\'importe quel endroit.',
    mobileAppsDesc: 'Applications iOS et Android conçues pour les entreprises.',
    mobileAppsDetail: 'Nous développons des applications mobiles qui étendent vos capacités aux smartphones et tablettes.',
    // Industries CTAs
    findYourSolution: 'Trouver Votre Solution',
    contactSales: 'Contacter les Ventes',
    // Cookie Banner
    cookieTitle: 'Nous utilisons des cookies',
    cookieBody: 'Nous utilisons des cookies pour améliorer votre expérience, analyser le trafic et personnaliser le contenu. En cliquant sur "Accepter", vous consentez à notre utilisation des cookies conformément à notre',
    cookieAnd: 'et',
    cookieCompliance: 'Ce site est conforme au Règlement Nigérian sur la Protection des Données (NDPR) et au RGPD.',
    cookieDecline: 'Refuser',
    cookieAccept: 'Tout Accepter',
    // Testimonials / Partners placeholders
    testimonialsHeading: 'Témoignages',
    partnersHeading: 'Nos Partenaires',
    // Featured Projects CTAs
    startAProject: 'Démarrer un Projet',
    viewCaseStudies: 'Voir les Études de Cas',
    // About CTA
    readyToWorkWithUs: 'Prêt à travailler avec nous ?',
    aboutCtaSub: "Parlez à notre équipe de vos besoins technologiques — nous construirons une solution autour de votre entreprise.",
    contactUs: 'Nous Contacter',
    viewOurSolutions: 'Voir Nos Solutions',
    // Locations
    contactThisOffice: 'Contacter ce Bureau',
    viewOnMap: 'Voir sur la Carte',
    // Not Found
    pageNotFound: 'Page Introuvable',
    pageNotFoundSub: 'La page que vous recherchez n\'existe pas ou a été déplacée. Laissez-nous vous remettre sur la bonne voie.',
    backToHomepage: 'Retour à l\'Accueil',
    goBack: 'Retour',
    // Careers
    viewOpenRoles: 'Voir les Postes Ouverts',
    learnAboutCulture: 'Découvrir Notre Culture',
    applyForGraduate: 'Postuler au Programme Diplômé',
    applyForInternship: 'Postuler au Stage',
    apply: 'Postuler',
    submitApplication: 'Soumettre la Candidature',
    // Support
    raiseATicket: 'Soumettre un Ticket',
    callSupportNow: 'Appeler le Support',
    requestAccess: 'Demander l\'Accès',
    submitRequest: 'Soumettre la Demande',
    // Blog
    readLatestPosts: 'Lire les Derniers Articles',
    subscribeForUpdates: 'S\'abonner aux Mises à Jour',
    subscribe: 'S\'abonner',
    // EdTech
    partnerWithUs: 'Devenir Partenaire',
    viewProgrammes: 'Voir les Programmes',
    visitEdTechWebsite: 'Visiter le Site EdTech',
    submitEnquiry: 'Soumettre la Demande',
    // Billboard / Rentals
    requestAQuote: 'Demander un Devis',
    requestARental: 'Demander une Location',
    viewEquipment: 'Voir l\'Équipement',
    // Navbar solutions mega menu categories
    catAVInfra: 'AV & Infrastructure',
    catSoftwareApps: 'Logiciels & Applications',
    catManagedCloud: 'Géré & Cloud',
    catSpecialist: 'Spécialiste',
    // Featured Projects content
    proj1Solution: 'Solution NOC 15 Écrans',
    proj1Category: 'NOC & Centre de Commandement',
    proj1Outcome: 'Déploiement d\'un centre d\'opérations réseau de 15 écrans permettant une surveillance en temps réel de l\'infrastructure UBA.',
    proj2Solution: 'Videowall 4x2 46 Pouces avec Solution de Surveillance NOC',
    proj2Category: 'Videowall & NOC',
    proj2Outcome: 'Installation d\'un videowall haute résolution de 8 panneaux pour la surveillance centralisée du réseau et de la sécurité.',
    proj3Solution: 'Solution Centre de Commandement pour la Surveillance des Liens et de l\'Infrastructure',
    proj3Category: 'Conception, Déploiement & Support',
    proj3Outcome: 'Solution de centre de commandement de bout en bout pour la surveillance des liens et de l\'infrastructure sur le campus universitaire.',
    proj4Solution: 'Solution NOC 32 Écrans',
    proj4Category: 'NOC & Centre de Commandement',
    proj4Outcome: 'Déploiement d\'un centre d\'opérations réseau de 32 écrans pour Access Bank DIG, permettant une surveillance complète de l\'infrastructure.',
    proj5Solution: 'Videowall NOC avec Support de Sol Peerless',
    proj5Category: 'Videowall & NOC',
    proj5Outcome: 'Installation d\'un videowall NOC haute résolution avec support de sol Peerless au siège de FCMB Lagos.',
    proj6Solution: 'Solution Centre de Commandement pour la Surveillance de l\'Infrastructure',
    proj6Category: 'Conception, Déploiement & Support',
    proj6Outcome: 'Déploiement d\'une solution de centre de commandement pour la surveillance de l\'infrastructure dans les bureaux d\'ePROCESS à Accra, Ghana.',
    proj7Solution: 'Solution Logitech VC Multi-Sites',
    proj7Category: 'AV & Collaboration',
    proj7Outcome: 'Mise en œuvre d\'une solution de vidéoconférence Logitech multi-sites à Lagos, Bonny, Port Harcourt et Abuja.',
    // Hero slides
    slide0Eyebrow: 'Solutions Technologiques d\'Entreprise',
    slide0Title: 'Propulser l\'Avenir',
    slide0Accent: 'Numérique de l\'Afrique',
    slide0Sub: 'Connectivité, infrastructure et services gérés de classe mondiale pour les entreprises à travers l\'Afrique — fiables et conçus pour la croissance.',

    slide1Eyebrow: 'Événement à Venir — 6 Mai 2026',
    slide1Title: 'Huawei IdeaHub S3',
    slide1Accent: 'Lancement',
    slide1Sub: 'Découvrez l\'Avenir de la Collaboration Intelligente. Rejoignez-nous au Four Points by Sheraton, VI, Lagos. 10h00 WAT.',
    slide1EventDate: '6 Mai 2026',
    slide1EventTime: '10h00 WAT',
    slide1EventVenue: 'Four Points by Sheraton, VI, Lagos',
    slide1EventCta: 'S\'inscrire',

    slide2Eyebrow: 'Solutions pour Écoles Intelligentes',
    slide2Title: 'Former la Prochaine',
    slide2Accent: 'Génération de Talents',
    slide2Sub: 'Proxynet EdTech déploie des salles de classe intelligentes, des programmes d\'alphabétisation numérique et des infrastructures TIC dans les écoles d\'Afrique de l\'Ouest.',

    slide3Eyebrow: 'NOC & Centres de Commandement',
    slide3Title: 'Surveillance en Temps Réel',
    slide3Accent: 'à Grande Échelle',
    slide3Sub: 'Des solutions NOC à 15 écrans aux centres de commandement complets — nous concevons et déployons l\'infrastructure qui garde vos opérations visibles.',

    slide4Eyebrow: 'Intégration de Systèmes',
    slide4Title: 'Une Technologie Qui',
    slide4Accent: 'Fonctionne Ensemble',
    slide4Sub: 'Nous connectons votre matériel, vos logiciels et vos réseaux en un système unifié — éliminant les silos et améliorant l\'efficacité opérationnelle.',

    slide5Eyebrow: 'Solutions AV & Videowalls',
    slide5Title: 'Des Écrans Qui',
    slide5Accent: 'Captent l\'Attention',
    slide5Sub: 'Des videowalls de salle de réunion aux événements AV à grande échelle — nous concevons, déployons et supportons des solutions d\'affichage de classe mondiale.',

    slide6Eyebrow: 'Cybersécurité',
    slide6Title: 'Protéger Votre',
    slide6Accent: 'Infrastructure',
    slide6Sub: 'Pare-feux, détection d\'intrusion, VPN et reprise après sinistre — nous sécurisons votre entreprise contre les menaces internes et externes.',
    projectsDelivered: 'Projets Réalisés',
    countriesServed: 'Pays Desservis',
    globalPartners: 'Partenaires Technologiques Mondiaux',
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = translations[lang]
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
