import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const translations = {
  en: {
    // Nav
    getInTouch: 'Get in Touch',
    search: 'Search Proxynet…',
    home: 'Home',
    about: 'About',
    solutions: 'Solutions',
    casestudies: 'Case Studies',
    support: 'Support',
    blog: 'Blog',
    connectivity: 'Connectivity',
    infrastructure: 'Infrastructure',
    managedServices: 'Managed Services',
    internetServices: 'Internet Services',
    vsatSolutions: 'VSAT Solutions',
    dataCentre: 'Data Centre',
    cybersecurity: 'Cybersecurity',
    itSupport: 'IT Support',
    cloudServices: 'Cloud Services',
    // Solutions (real)
    itSecurity: 'IT Security & Disaster Recovery',
    systemsIntegration: 'Systems Integration',
    enterpriseNetworking: 'Enterprise Networking',
    securityAwareness: 'Security Awareness Programs',
    policyDevelopment: 'Policy Development',
    disasterRecovery: 'Disaster Recovery',
    incidentResponse: 'Incident Response',
    intrusionDetection: 'Intrusion Detection',
    remoteAccess: 'Remote Access Solutions',
    firewallSecurity: 'Firewall Security',
    antiVirus: 'Anti-Virus Consulting',
    vpn: 'Virtual Private Networking (VPN)',
    logsMonitoring: 'Logs & Server Monitoring',
    // Software
    softwareSolutions: 'Software Solutions',
    customDev: 'Custom Software Development',
    webApps: 'Web Applications',
    mobileApps: 'Mobile Applications',
    erp: 'ERP & Business Systems',
    // Rentals & Billboard
    rentals: 'AV Equipment Rentals',
    rentalsDesc: 'World-class AV equipment for events and activations.',
    billboardSolutions: 'Billboard & Digital Signage',
    billboardDesc: 'Indoor and outdoor digital signage and LED wall deployments.',
    // Footer
    footerTagline: "Connecting Nigeria's future with world-class technology infrastructure and managed services.",
    company: 'Company',
    aboutUs: 'About Us',
    ourTeam: 'Our Team',
    careers: 'Careers',
    newsPress: 'News & Press',
    partners: 'Partners',
    resources: 'Resources',
    whitepapers: 'Whitepapers',
    supportCentre: 'Support Centre',
    faqs: 'FAQs',
    contact: 'Contact',
    stayUpdated: 'Stay updated',
    emailPlaceholder: 'Your email address',
    thankYou: 'Thanks for subscribing!',
    privacyPolicy: 'Privacy Policy',
    cookiePolicy: 'Cookie Policy',
    terms: 'Terms & Conditions',
    copyright: `© ${new Date().getFullYear()} Proxynet Group Ltd. RC 472270. All rights reserved.`,
    // Home
    heroEyebrow: 'Enterprise Technology Solutions',
    heroTitle: 'Powering Africa\'s',
    heroTitleAccent: 'Digital Future',
    heroSub: 'World-class connectivity, infrastructure, and managed services for businesses across Africa — built for reliability, designed for growth.',
    exploreSolutions: 'Explore Solutions',
    // Final CTA
    finalCtaHeading: 'Ready to Transform Your IT Infrastructure?',
    finalCtaSub: 'Talk to our team and get a solution tailored to your business needs.',
    // Projects
    projectsEyebrow: 'Featured Projects',
    projectsHeading: 'Work We\'re Proud Of',
    // Blog
    latestInsights: 'Latest Insights',
    viewAll: 'View all posts',
    readMore: 'Read more',
    // Support CTA
    supportEyebrow: 'Customer Success',
    supportHeading: "We don't just deploy, we support you.",
    supportSub: "Our relationship doesn't end at installation. We provide ongoing support, monitoring, and maintenance to ensure your technology keeps working — long after the project is delivered.",
    supportCTALabel: 'Visit our Support Centre',
    supportPillar1: '24/7 monitoring and incident response',
    supportPillar2: 'Dedicated support engineers on call',
    supportPillar3: 'Long-term partnerships, not one-off projects',
    // Industries
    industriesEyebrow: 'Industries We Serve',
    industriesHeading: 'Built for the Sectors That Drive Africa\'s Economy',
    industriesSub: 'We\'ve delivered technology solutions across a wide range of industries — each with its own demands, regulations, and infrastructure challenges.',
    indFinancial: 'Financial Services',
    indFinancialDesc: 'Secure networks and compliance-ready infrastructure for banks and fintechs.',
    indOilGas: 'Oil & Gas',
    indOilGasDesc: 'Rugged connectivity and monitoring systems for upstream and downstream operations.',
    indManufacturing: 'Manufacturing',
    indManufacturingDesc: 'Systems integration and network solutions for factory floors and supply chains.',
    indTelecoms: 'Telecoms',
    indTelecomsDesc: 'Enterprise networking and managed services for telecoms operators.',
    indGovernment: 'Government',
    indGovernmentDesc: 'Secure, scalable IT infrastructure for public sector agencies and ministries.',
    indEducation: 'Education',
    indEducationDesc: 'Campus networks, smart classrooms, and e-learning infrastructure.',
    indHealthcare: 'Healthcare',
    indHealthcareDesc: 'Reliable connectivity and data security for hospitals and clinics.',
    indRetail: 'Retail',
    indRetailDesc: 'Smart signage, POS networks, and digital infrastructure for retail environments.',
    // What We Do
    whatWeDoEyebrow: 'What We Do',
    whatWeDoHeading: 'We Build & Manage Technology Infrastructure',
    whatWeDoClarity: 'We design, deploy, and support the technology systems that keep your business running — from networks and security to software and smart displays.',
    justSoYouKnow: 'Just so you know',
    whatWeDoExplainer: 'Proxynet is a technology solutions company — not an events organiser. We help businesses across Africa build reliable IT infrastructure, secure their networks, and develop software. If you\'ve heard otherwise, we\'re glad you\'re here to find out what we actually do.',
    lfdSignage: 'LFD & Smart Signage',
    lfdSignageDesc: 'Large format display systems for boardrooms, lobbies, and public spaces.',
    lfdSignageDetail: 'We design and install large format display (LFD) and smart signage solutions — from single-screen boardroom setups to multi-zone digital signage networks across campuses and retail environments.',
    systemsIntegrationDesc: 'Connecting your hardware, software, and networks into one seamless system.',
    systemsIntegrationDetail: 'We integrate disparate technology systems so they communicate and work together — reducing manual processes, eliminating data silos, and giving your team a unified view of operations.',
    enterpriseSoftware: 'Enterprise Software Development',
    enterpriseSoftwareDesc: 'Custom business applications built around your workflows.',
    enterpriseSoftwareDetail: 'From ERP systems to bespoke internal tools, we develop enterprise software that fits how your organisation actually works — not the other way around.',
    enterpriseNetworkingDesc: 'LAN, MAN, and WAN solutions designed for performance and reliability.',
    enterpriseNetworkingDetail: 'We design and implement scalable network infrastructure — local area networks, wide area networks, and everything in between — built to handle your current load and grow with you.',
    networkSecurity: 'Network Security',
    networkSecurityDesc: 'Protecting your infrastructure from threats, inside and out.',
    networkSecurityDetail: 'Our security team implements firewalls, intrusion detection systems, anti-virus solutions, and VPNs to protect your organisation from both external attacks and internal vulnerabilities.',
    disasterRecoveryDesc: 'Keeping your data safe and your business running when things go wrong.',
    disasterRecoveryDetail: 'We plan, implement, and regularly test disaster recovery strategies so that when the unexpected happens — hardware failure, cyberattack, or natural disaster — your business recovers fast.',
    enterpriseNetworkingWan: 'Remote Access & VPN',
    enterpriseNetworkingWanDesc: 'Secure connectivity for teams working from anywhere.',
    enterpriseNetworkingWanDetail: 'We implement remote access solutions and VPN infrastructure that let your team connect securely to company systems from any location, without compromising security.',
    mobileAppsDesc: 'iOS and Android applications built for business.',
    mobileAppsDetail: 'We build mobile applications that extend your business capabilities to smartphones and tablets — whether customer-facing apps or internal tools for field teams.',
    // Stats
    yearsInOperation: 'Years of Experience',
    projectsDelivered: 'Projects Delivered',
    countriesServed: 'Countries Served',
    globalPartners: 'Global Technology Partners',
  },
  fr: {
    // Nav
    getInTouch: 'Nous Contacter',
    search: 'Rechercher Proxynet…',
    home: 'Accueil',
    about: 'À Propos',
    solutions: 'Solutions',
    casestudies: 'Études de Cas',
    support: 'Assistance',
    blog: 'Blog',
    connectivity: 'Connectivité',
    infrastructure: 'Infrastructure',
    managedServices: 'Services Gérés',
    internetServices: 'Services Internet',
    vsatSolutions: 'Solutions VSAT',
    dataCentre: 'Centre de Données',
    cybersecurity: 'Cybersécurité',
    itSupport: 'Support IT',
    cloudServices: 'Services Cloud',
    // Solutions (real)
    itSecurity: 'Sécurité IT & Reprise après Sinistre',
    systemsIntegration: 'Intégration de Systèmes',
    enterpriseNetworking: 'Réseaux d\'Entreprise',
    securityAwareness: 'Programmes de Sensibilisation',
    policyDevelopment: 'Développement de Politiques',
    disasterRecovery: 'Reprise après Sinistre',
    incidentResponse: 'Réponse aux Incidents',
    intrusionDetection: 'Détection d\'Intrusion',
    remoteAccess: 'Solutions d\'Accès à Distance',
    firewallSecurity: 'Sécurité Pare-feu',
    antiVirus: 'Conseil Anti-Virus',
    vpn: 'Réseau Privé Virtuel (VPN)',
    logsMonitoring: 'Surveillance des Journaux & Serveurs',
    // Software
    softwareSolutions: 'Solutions Logicielles',
    customDev: 'Développement Logiciel Sur Mesure',
    webApps: 'Applications Web',
    mobileApps: 'Applications Mobiles',
    erp: 'ERP & Systèmes d\'Entreprise',
    // Rentals & Billboard
    rentals: 'Location d\'Équipement AV',
    rentalsDesc: 'Équipement AV de classe mondiale pour événements.',
    billboardSolutions: 'Affichage & Signalétique Numérique',
    billboardDesc: 'Déploiements de signalétique numérique intérieure et extérieure.',
    // Footer
    footerTagline: "Connecter l'avenir du Nigeria avec une infrastructure technologique de classe mondiale et des services gérés.",
    company: 'Entreprise',
    aboutUs: 'À Propos',
    ourTeam: 'Notre Équipe',
    careers: 'Carrières',
    newsPress: 'Actualités & Presse',
    partners: 'Partenaires',
    resources: 'Ressources',
    whitepapers: 'Livres Blancs',
    supportCentre: "Centre d'Assistance",
    faqs: 'FAQ',
    contact: 'Contact',
    stayUpdated: 'Restez informé',
    emailPlaceholder: 'Votre adresse email',
    thankYou: 'Merci pour votre inscription!',
    privacyPolicy: 'Politique de Confidentialité',
    cookiePolicy: 'Politique des Cookies',
    terms: 'Conditions Générales',
    copyright: `© ${new Date().getFullYear()} Proxynet Group Ltd. RC 472270. Tous droits réservés.`,
    // Home
    heroEyebrow: 'Solutions Technologiques d\'Entreprise',
    heroTitle: 'Propulser l\'Avenir',
    heroTitleAccent: 'Numérique de l\'Afrique',
    heroSub: 'Connectivité, infrastructure et services gérés de classe mondiale pour les entreprises à travers l\'Afrique — fiables et conçus pour la croissance.',
    exploreSolutions: 'Explorer les Solutions',
    // Final CTA
    finalCtaHeading: 'Prêt à Transformer Votre Infrastructure IT?',
    finalCtaSub: 'Parlez à notre équipe et obtenez une solution adaptée à vos besoins.',
    // Projects
    projectsEyebrow: 'Projets en Vedette',
    projectsHeading: 'Des Réalisations dont Nous Sommes Fiers',
    // Blog
    latestInsights: 'Dernières Actualités',
    viewAll: 'Voir tous les articles',
    readMore: 'Lire la suite',
    // Support CTA
    supportEyebrow: 'Succès Client',
    supportHeading: "Nous ne faisons pas que déployer, nous vous accompagnons.",
    supportSub: "Notre relation ne s'arrête pas à l'installation. Nous fournissons un support continu, une surveillance et une maintenance pour que votre technologie continue de fonctionner.",
    supportCTALabel: "Visiter notre Centre d'Assistance",
    supportPillar1: 'Surveillance et réponse aux incidents 24h/24 7j/7',
    supportPillar2: 'Ingénieurs support dédiés disponibles',
    supportPillar3: 'Partenariats à long terme, pas des projets ponctuels',
    // Industries
    industriesEyebrow: 'Secteurs que Nous Servons',
    industriesHeading: 'Conçu pour les Secteurs qui Propulsent l\'Économie Africaine',
    industriesSub: 'Nous avons livré des solutions technologiques dans de nombreux secteurs — chacun avec ses propres exigences et défis.',
    indFinancial: 'Services Financiers',
    indFinancialDesc: 'Réseaux sécurisés et infrastructure conforme pour banques et fintechs.',
    indOilGas: 'Pétrole & Gaz',
    indOilGasDesc: 'Connectivité robuste et systèmes de surveillance pour les opérations pétrolières.',
    indManufacturing: 'Industrie Manufacturière',
    indManufacturingDesc: 'Intégration de systèmes et solutions réseau pour les usines et chaînes d\'approvisionnement.',
    indTelecoms: 'Télécommunications',
    indTelecomsDesc: 'Réseaux d\'entreprise et services gérés pour les opérateurs télécoms.',
    indGovernment: 'Gouvernement',
    indGovernmentDesc: 'Infrastructure IT sécurisée et évolutive pour les agences du secteur public.',
    indEducation: 'Éducation',
    indEducationDesc: 'Réseaux de campus, salles de classe intelligentes et infrastructure e-learning.',
    indHealthcare: 'Santé',
    indHealthcareDesc: 'Connectivité fiable et sécurité des données pour hôpitaux et cliniques.',
    indRetail: 'Commerce de Détail',
    indRetailDesc: 'Affichage dynamique, réseaux PDV et infrastructure numérique pour la vente au détail.',
    // What We Do
    whatWeDoEyebrow: 'Ce Que Nous Faisons',
    whatWeDoHeading: 'Nous Construisons et Gérons l\'Infrastructure Technologique',
    whatWeDoClarity: 'Nous concevons, déployons et supportons les systèmes technologiques qui font fonctionner votre entreprise.',
    justSoYouKnow: 'Pour info',
    whatWeDoExplainer: 'Proxynet est une entreprise de solutions technologiques — pas un organisateur d\'événements. Nous aidons les entreprises africaines à construire une infrastructure IT fiable, sécuriser leurs réseaux et développer des logiciels.',
    lfdSignage: 'LFD & Affichage Dynamique',
    lfdSignageDesc: 'Systèmes d\'affichage grand format pour salles de réunion et espaces publics.',
    lfdSignageDetail: 'Nous concevons et installons des solutions d\'affichage grand format (LFD) et de signalétique numérique — des configurations de salle de réunion aux réseaux d\'affichage multi-zones.',
    systemsIntegrationDesc: 'Connecter votre matériel, logiciels et réseaux en un système unifié.',
    systemsIntegrationDetail: 'Nous intégrons des systèmes technologiques disparates pour qu\'ils communiquent et fonctionnent ensemble — réduisant les processus manuels et éliminant les silos de données.',
    enterpriseSoftware: 'Développement Logiciel d\'Entreprise',
    enterpriseSoftwareDesc: 'Applications métier personnalisées construites autour de vos flux de travail.',
    enterpriseSoftwareDetail: 'Des systèmes ERP aux outils internes sur mesure, nous développons des logiciels d\'entreprise qui s\'adaptent à votre organisation.',
    enterpriseNetworkingDesc: 'Solutions LAN, MAN et WAN conçues pour la performance et la fiabilité.',
    enterpriseNetworkingDetail: 'Nous concevons et mettons en œuvre une infrastructure réseau évolutive — réseaux locaux, étendus et tout ce qui se trouve entre les deux.',
    networkSecurity: 'Sécurité Réseau',
    networkSecurityDesc: 'Protéger votre infrastructure contre les menaces internes et externes.',
    networkSecurityDetail: 'Notre équipe de sécurité met en œuvre des pare-feux, des systèmes de détection d\'intrusion, des solutions antivirus et des VPN.',
    disasterRecoveryDesc: 'Garder vos données en sécurité et votre entreprise opérationnelle en cas de problème.',
    disasterRecoveryDetail: 'Nous planifions, mettons en œuvre et testons régulièrement des stratégies de reprise après sinistre pour une récupération rapide.',
    enterpriseNetworkingWan: 'Accès à Distance & VPN',
    enterpriseNetworkingWanDesc: 'Connectivité sécurisée pour les équipes travaillant de partout.',
    enterpriseNetworkingWanDetail: 'Nous mettons en œuvre des solutions d\'accès à distance et une infrastructure VPN pour une connexion sécurisée depuis n\'importe quel endroit.',
    mobileAppsDesc: 'Applications iOS et Android conçues pour les entreprises.',
    mobileAppsDetail: 'Nous développons des applications mobiles qui étendent vos capacités aux smartphones et tablettes.',
    // Stats
    yearsInOperation: "Années d'Expérience",
    projectsDelivered: 'Projets Réalisés',
    countriesServed: 'Pays Desservis',
    globalPartners: 'Partenaires Technologiques Mondiaux',
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = translations[lang]
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
